// ============================================
// DEFENSE SIGNAL MONITOR — Application Logic
// Restructured: Theater strip, ETF chart, clean tabs
// ============================================

// === UTILITY: Create ticker link ===
function tickerLink(ticker) {
    return `<a href="https://perplexity.ai/finance/${ticker}" target="_blank" rel="noopener" class="ticker-link">${ticker}</a>`;
}

// === UTILITY: Linkify tickers in text ===
const ALL_TICKERS = ["LMT","RTX","NOC","GD","BA","LHX","HII","BWXT","CW","KTOS","RKLB","PLTR","AVAV","BAESY","MRCY","LDOS","SAIC","BAH","FTNT","CRWD","PANW","JOBY","ACHR","CVX","MSFT","SPY","ITA"];
const UNIQUE_TICKERS = [...new Set(ALL_TICKERS)];

function linkifyTickers(text) {
    const sorted = UNIQUE_TICKERS.slice().sort((a, b) => b.length - a.length);
    let result = text;
    sorted.forEach(ticker => {
        const regex = new RegExp(`(?<![\\w/">])\\b(${ticker})\\b(?![^<]*<\\/a>)(?![-\\w])`, 'g');
        result = result.replace(regex, `<a href="https://perplexity.ai/finance/${ticker}" target="_blank" rel="noopener" class="ticker-link">$1</a>`);
    });
    return result;
}

// === STOCK DATA ===
const stockData = [
    { ticker: "LMT", company: "Lockheed Martin", price: 658.08, dayChange: 2.56, score: 5, direction: "bullish", summary: "OPERATION EPIC FURY: F-35/F-22 engaged in Iran strikes. PAC-3 intercepting Iranian missiles. Record $194B backlog. Morningstar: defense becoming subscription model. F-47 win. $480M Navy ASW contract. 6 politician buys. Expect significant Monday gap up." },
    { ticker: "RTX", company: "Raytheon Technologies", price: 202.62, dayChange: 2.52, score: 5, direction: "bullish", summary: "OPERATION EPIC FURY: Tomahawk missiles fired at Iran. Patriot batteries intercepting Iranian retaliation. $50B sustainment through 2045. StormBreaker approved. Most Congress-traded defense stock. Iran strikes = unprecedented Patriot/Tomahawk demand validation." },
    { ticker: "NOC", company: "Northrop Grumman", price: 724.38, dayChange: 1.90, score: 5, direction: "bullish", summary: "OPERATION EPIC FURY: B-21 Raiders engaged in Iran strikes — combat-validated for second time. Production +25% ($4.5B) in reconciliation. Midnight Hammer repeat confirmed. Sentinel ICBM. Nuclear modernization centerpiece. IDF struck 'hundreds of military sites.'" },
    { ticker: "KTOS", company: "Kratos Defense", price: 86.18, dayChange: -6.47, score: 3, direction: "neutral", summary: "DOWNGRADED: -5.90% selloff despite $12.4M CCA engine contract (Feb 23, AFA) and $1.1B Drone Dominance. Market skepticism on execution timeline. Momentum deterioration." },
    { ticker: "RKLB", company: "Rocket Lab USA", price: 69.10, dayChange: -4.89, score: 4, direction: "bullish", summary: "$816M SDA satellite contract. Golden Dome missile defense. SDA HALO tactical SATCOM demo ecosystem. Space-based tracking." },
    { ticker: "BWXT", company: "BWX Technologies", price: 205.98, dayChange: -0.61, score: 5, direction: "bullish", summary: "Nuclear emphasis in $153B reconciliation spend. Sole-source naval nuclear. Active carrier operations in Iran theater = accelerated nuclear submarine demand. Zero DOGE risk. Record $7.4B backlog. B-21 nuclear systems engaged." },
    { ticker: "HII", company: "Huntington Ingalls", price: 444.52, dayChange: 0.34, score: 5, direction: "bullish", summary: "OPERATION EPIC FURY: Dual carrier strike groups (Ford + Lincoln) + 25-35 surface vessels engaged. CENTCOM: 'Armada fully operational.' $29B shipbuilding in reconciliation. Only nuclear shipyard. Naval assets in active combat operations." },
    { ticker: "CW", company: "Curtiss-Wright", price: 700.33, dayChange: -0.24, score: 4, direction: "bullish", summary: "Sole-source naval nuclear controls. Zero DOGE risk. AFA Warfare Symposium acquisition reform tailwind." },
    { ticker: "GD", company: "General Dynamics", price: 357.05, dayChange: 1.80, score: 3, direction: "bullish", summary: "Virginia-class sub production. Franklin bought day after $1.32B contract. Columbia-class ramp. SSGN deployment confirmed." },
    { ticker: "LHX", company: "L3Harris Technologies", price: 364.54, dayChange: 2.64, score: 5, direction: "bullish", summary: "UPGRADED TO 5: Active combat operations = maximum EW/comms/sensor demand. F-22 Raptors engaged in Iran. Every aircraft in theater uses L3Harris electronic warfare and communications gear. Book-to-bill 1.5x. Iran strikes validate entire product line." },
    { ticker: "PLTR", company: "Palantir Technologies", price: 137.19, dayChange: 0.92, score: 5, direction: "bullish", summary: "UPGRADED TO 5: OpenAI wins Pentagon AI contract after Anthropic designated 'supply-chain risk to national security.' PLTR incumbent AI/targeting platform benefits from active combat ops. Real-time battlefield intelligence demand surging. $10B Army contract." },
    { ticker: "AVAV", company: "AeroVironment", price: 252.25, dayChange: -2.84, score: 3, direction: "bullish", summary: "Switchblade Ukraine demand. BlueHalo acquisition. Iran escalation = loitering munitions demand surge. Ukraine front stabilizing." },
    { ticker: "BAESY", company: "BAE Systems ADR", price: 116.00, dayChange: 0.91, score: 4, direction: "bullish", summary: "UPGRADED: $500M+ Army Paladin howitzer contract (Feb 27). European NATO re-arming supercycle. Iran strikes = allied rearmament acceleration. Front-line states accelerating spending. +16.29% in 10-day backtest." },
    { ticker: "MRCY", company: "Mercury Systems", price: 89.03, dayChange: -0.61, score: 3, direction: "bullish", summary: "CEO turnaround. Embedded in F-35/Patriot. Iran crisis = accelerated Patriot/F-35 procurement." },
    { ticker: "BA", company: "Boeing", price: 227.53, dayChange: -0.82, score: 2, direction: "neutral", summary: "F-47 NGAD win. CCA weapon integration testing begun (YFQ-44A inert AIM-120 Feb 23). BUT commercial crisis, high leverage." },
    { ticker: "LDOS", company: "Leidos Holdings", price: 175.10, dayChange: -0.43, score: 2, direction: "neutral", summary: "DOGE risk materializing. Navy NGEN. DOGE cuts hitting IT services." },
    { ticker: "FTNT", company: "Fortinet", price: 79.03, dayChange: -0.21, score: 1, direction: "neutral", summary: "OT/ICS security growth. Google-Wiz deal ($32B) competitive threat. Chinese/Iranian APTs targeting defense industry (Feb 17 Dragos report)." },
    { ticker: "CRWD", company: "CrowdStrike", price: 371.98, dayChange: -2.39, score: 0, direction: "bearish", summary: "DOWNGRADED TO EXCLUDED: Earnings miss — stock -9.85% Feb 23. Execution failure. Moved to excluded on negative momentum despite persistent cyber demand." },
    { ticker: "JOBY", company: "Joby Aviation", price: 10.06, dayChange: -1.66, score: 1, direction: "neutral", summary: "Military logistics potential. But pre-revenue, limited defense utility." },
    { ticker: "ACHR", company: "Archer Aviation", price: 7.12, dayChange: -3.52, score: 0, direction: "neutral", summary: "Limited defense utility. eVTOL speculation." },
    { ticker: "PANW", company: "Palo Alto Networks", price: 148.92, dayChange: -0.32, score: -1, direction: "bearish", summary: "Platformization headwinds. Near 52-week low. Google-Wiz deal pressuring valuation. APT competition heating." },
    { ticker: "SAIC", company: "Science Applications", price: 92.26, dayChange: 0.61, score: -2, direction: "bearish", summary: "$95M GAO IT modernization contract win (Feb 27). Still DOGE-exposed but new contract provides some cushion. Upgrading from -3 to -2." },
    { ticker: "BAH", company: "Booz Allen Hamilton", price: 78.83, dayChange: -1.18, score: -3, direction: "bearish", summary: "DOGE devastation offset: $697M Army MCTP training contract win (Feb 27). Active combat operations = surge in training/simulation demand. But still DOGE-exposed on civil side. Upgrading from -5 to -3 on new contract." }
];

// === SIGNALS FEED DATA ===
const signalsFeedData = [
    { date: "2026-03-01", time: "14:00", tag: "MILTRACK", tagClass: "miltrack", text: '<strong>3 US service members killed, 5 seriously wounded</strong> in Iranian retaliatory strikes on US installations in the Gulf region. CENTCOM confirms casualties from ballistic missile and drone attacks on bases in Bahrain and UAE. First US KIA since Operation Epic Fury began. <strong>TICKERS: LMT, RTX, NOC, HII, GD, LHX.</strong>', recent: true, sources: [{"name": "CENTCOM", "url": "https://www.centcom.mil/"}, {"name": "@sentdefender", "url": "https://x.com/sentdefender"}] },
    { date: "2026-03-01", time: "12:00", tag: "CYBER", tagClass: "cyber", text: 'WSJ: CENTCOM used Anthropic Claude AI during Operation Epic Fury strikes <strong>despite Anthropic being designated a \'supply-chain risk to national security\'</strong> by Pentagon. AI used for targeting analysis and battle damage assessment. Raises questions about DoD AI procurement and Anthropic\'s classified access status. <strong>TICKERS: PLTR.</strong>', recent: true, sources: [{"name": "Wall Street Journal", "url": "https://www.wsj.com/"}, {"name": "@sentdefender", "url": "https://x.com/sentdefender"}] },
    { date: "2026-03-01", time: "10:00", tag: "MILTRACK", tagClass: "miltrack", text: 'Fox News: <strong>1,000+ Iranian military sites struck in first 24 hours</strong> of Operation Epic Fury. US and Israeli forces continue round-the-clock operations. Pentagon describes campaign as \'most intensive aerial campaign since Iraq 2003.\' <strong>TICKERS: LMT, RTX, NOC, LHX, HII, BWXT.</strong>', recent: true, sources: [{"name": "Fox News", "url": "https://www.foxnews.com/"}, {"name": "@sentdefender", "url": "https://x.com/sentdefender"}] },
    { date: "2026-03-01", time: "08:00", tag: "OSINT", tagClass: "osint", text: 'Iran continues retaliatory strikes on Bahrain — <strong>smoke rising from Manama</strong> visible in satellite imagery and social media. Iranian ballistic missiles targeting US Naval Support Activity Bahrain (5th Fleet HQ). Gulf state infrastructure under sustained attack. <strong>TICKERS: LMT, RTX, NOC, HII, GD.</strong>', recent: true, sources: [{"name": "@sentdefender", "url": "https://x.com/sentdefender"}] },
    { date: "2026-03-01", time: "06:00", tag: "OSINT", tagClass: "osint", text: 'Politico: <strong>Pentagon offers no evidence of imminent threat</strong> that justified Operation Epic Fury. Critics question legal basis for strikes. Administration cites 2001/2002 AUMFs and Article II powers. Congress demands briefing. <strong>TICKERS: LMT, RTX, NOC.</strong>', recent: true, sources: [{"name": "Politico", "url": "https://www.politico.com/"}] },
    { date: "2026-03-01", time: "04:00", tag: "CONTRACT", tagClass: "contract", text: 'Photonis Defense awarded <strong>$352.6M Army contract</strong> for Binocular Night Observation Device (BiNOD) systems. Multi-year procurement for next-gen night vision across infantry units. <strong>Night vision/optics supply chain beneficiary.</strong>', recent: true, sources: [{"name": "DoD Contracts", "url": "https://www.defense.gov/News/Contracts/"}] },
    { date: "2026-03-01", time: "02:00", tag: "CONTRACT", tagClass: "contract", text: 'UK awards Leonardo <strong>£1B military helicopter contract</strong> (Reuters). Covers AW149 medium-lift helicopters for British Army to replace aging Puma fleet. European defense spending acceleration continues. <strong>TICKERS: BAESY (European defense proxy).</strong>', recent: true, sources: [{"name": "Reuters", "url": "https://www.reuters.com/"}] },
    { date: "2026-03-01", time: "14:00", tag: "MILTRACK", tagClass: "miltrack", text: '<strong>3 US service members killed, 5 seriously wounded</strong> in Iranian retaliatory strikes on US installations in the Gulf region. CENTCOM confirms casualties from ballistic missile and drone attacks on bases in Bahrain and UAE. First US KIA since Operation Epic Fury began. <strong>TICKERS: LMT, RTX, NOC, HII, GD, LHX.</strong>', recent: true, sources: [{"name": "CENTCOM", "url": "https://www.centcom.mil/"}, {"name": "@sentdefender", "url": "https://x.com/sentdefender"}] },
    { date: "2026-03-01", time: "12:00", tag: "CYBER", tagClass: "cyber", text: 'WSJ: CENTCOM used Anthropic Claude AI during Operation Epic Fury strikes <strong>despite Anthropic being designated a \'supply-chain risk to national security\'</strong> by Pentagon. AI used for targeting analysis and battle damage assessment. Raises questions about DoD AI procurement and Anthropic\'s classified access status. <strong>TICKERS: PLTR.</strong>', recent: true, sources: [{"name": "Wall Street Journal", "url": "https://www.wsj.com/"}, {"name": "@sentdefender", "url": "https://x.com/sentdefender"}] },
    { date: "2026-03-01", time: "10:00", tag: "MILTRACK", tagClass: "miltrack", text: 'Fox News: <strong>1,000+ Iranian military sites struck in first 24 hours</strong> of Operation Epic Fury. US and Israeli forces continue round-the-clock operations. Pentagon describes campaign as \'most intensive aerial campaign since Iraq 2003.\' <strong>TICKERS: LMT, RTX, NOC, LHX, HII, BWXT.</strong>', recent: true, sources: [{"name": "Fox News", "url": "https://www.foxnews.com/"}, {"name": "@sentdefender", "url": "https://x.com/sentdefender"}] },
    { date: "2026-03-01", time: "08:00", tag: "OSINT", tagClass: "osint", text: 'Iran continues retaliatory strikes on Bahrain — <strong>smoke rising from Manama</strong> visible in satellite imagery and social media. Iranian ballistic missiles targeting US Naval Support Activity Bahrain (5th Fleet HQ). Gulf state infrastructure under sustained attack. <strong>TICKERS: LMT, RTX, NOC, HII, GD.</strong>', recent: true, sources: [{"name": "@sentdefender", "url": "https://x.com/sentdefender"}] },
    { date: "2026-03-01", time: "06:00", tag: "OSINT", tagClass: "osint", text: 'Politico: <strong>Pentagon offers no evidence of imminent threat</strong> that justified Operation Epic Fury. Critics question legal basis for strikes. Administration cites 2001/2002 AUMFs and Article II powers. Congress demands briefing. <strong>TICKERS: LMT, RTX, NOC.</strong>', recent: true, sources: [{"name": "Politico", "url": "https://www.politico.com/"}] },
    { date: "2026-03-01", time: "04:00", tag: "CONTRACT", tagClass: "contract", text: 'Photonis Defense awarded <strong>$352.6M Army contract</strong> for Binocular Night Observation Device (BiNOD) systems. Multi-year procurement for next-gen night vision across infantry units. <strong>Night vision/optics supply chain beneficiary.</strong>', recent: true, sources: [{"name": "DoD Contracts", "url": "https://www.defense.gov/News/Contracts/"}] },
    { date: "2026-03-01", time: "02:00", tag: "CONTRACT", tagClass: "contract", text: 'UK awards Leonardo <strong>£1B military helicopter contract</strong> (Reuters). Covers AW149 medium-lift helicopters for British Army to replace aging Puma fleet. European defense spending acceleration continues. <strong>TICKERS: BAESY (European defense proxy).</strong>', recent: true, sources: [{"name": "Reuters", "url": "https://www.reuters.com/"}] },
    { date: "2026-03-01", time: "14:00", tag: "MILTRACK", tagClass: "miltrack", text: '<strong>3 US service members killed, 5 seriously wounded</strong> in Iranian retaliatory strikes on US installations in the Gulf region. CENTCOM confirms casualties from ballistic missile and drone attacks on bases in Bahrain and UAE. First US KIA since Operation Epic Fury began. <strong>TICKERS: LMT, RTX, NOC, HII, GD, LHX.</strong>', recent: true, sources: [{"name": "CENTCOM", "url": "https://www.centcom.mil/"}, {"name": "@sentdefender", "url": "https://x.com/sentdefender"}] },
    { date: "2026-03-01", time: "12:00", tag: "CYBER", tagClass: "cyber", text: 'WSJ: CENTCOM used Anthropic Claude AI during Operation Epic Fury strikes <strong>despite Anthropic being designated a \'supply-chain risk to national security\'</strong> by Pentagon. AI used for targeting analysis and battle damage assessment. Raises questions about DoD AI procurement and Anthropic\'s classified access status. <strong>TICKERS: PLTR.</strong>', recent: true, sources: [{"name": "Wall Street Journal", "url": "https://www.wsj.com/"}, {"name": "@sentdefender", "url": "https://x.com/sentdefender"}] },
    { date: "2026-03-01", time: "10:00", tag: "MILTRACK", tagClass: "miltrack", text: 'Fox News: <strong>1,000+ Iranian military sites struck in first 24 hours</strong> of Operation Epic Fury. US and Israeli forces continue round-the-clock operations. Pentagon describes campaign as \'most intensive aerial campaign since Iraq 2003.\' <strong>TICKERS: LMT, RTX, NOC, LHX, HII, BWXT.</strong>', recent: true, sources: [{"name": "Fox News", "url": "https://www.foxnews.com/"}, {"name": "@sentdefender", "url": "https://x.com/sentdefender"}] },
    { date: "2026-03-01", time: "08:00", tag: "OSINT", tagClass: "osint", text: 'Iran continues retaliatory strikes on Bahrain — <strong>smoke rising from Manama</strong> visible in satellite imagery and social media. Iranian ballistic missiles targeting US Naval Support Activity Bahrain (5th Fleet HQ). Gulf state infrastructure under sustained attack. <strong>TICKERS: LMT, RTX, NOC, HII, GD.</strong>', recent: true, sources: [{"name": "@sentdefender", "url": "https://x.com/sentdefender"}] },
    { date: "2026-03-01", time: "06:00", tag: "OSINT", tagClass: "osint", text: 'Politico: <strong>Pentagon offers no evidence of imminent threat</strong> that justified Operation Epic Fury. Critics question legal basis for strikes. Administration cites 2001/2002 AUMFs and Article II powers. Congress demands briefing. <strong>TICKERS: LMT, RTX, NOC.</strong>', recent: true, sources: [{"name": "Politico", "url": "https://www.politico.com/"}] },
    { date: "2026-03-01", time: "04:00", tag: "CONTRACT", tagClass: "contract", text: 'Photonis Defense awarded <strong>$352.6M Army contract</strong> for Binocular Night Observation Device (BiNOD) systems. Multi-year procurement for next-gen night vision across infantry units. <strong>Night vision/optics supply chain beneficiary.</strong>', recent: true, sources: [{"name": "DoD Contracts", "url": "https://www.defense.gov/News/Contracts/"}] },
    { date: "2026-03-01", time: "02:00", tag: "CONTRACT", tagClass: "contract", text: 'UK awards Leonardo <strong>£1B military helicopter contract</strong> (Reuters). Covers AW149 medium-lift helicopters for British Army to replace aging Puma fleet. European defense spending acceleration continues. <strong>TICKERS: BAESY (European defense proxy).</strong>', recent: true, sources: [{"name": "Reuters", "url": "https://www.reuters.com/"}] },
    { date: "2026-02-28", time: "22:30", tag: "OSINT", tagClass: "osint", text: 'Iranians celebrate in streets of Karaj and Galehdar City after reports of Supreme Leader Khamenei\'s death. @sentdefender: \'I\'ll miss our conversations\' — posts GIF referencing Khamenei. Regime collapse signals emerging. <strong>TICKERS: LMT, RTX, NOC, GD, LHX, HII, BWXT.</strong>', recent: true, sources: [{name: "@sentdefender", url: "https://x.com/sentdefender/status/2027876133039997364"}, {name: "@sentdefender", url: "https://x.com/sentdefender/status/2027877189488636270"}] },
    { date: "2026-02-28", time: "22:06", tag: "MILTRACK", tagClass: "miltrack", text: 'CENTCOM debunks Iranian propaganda: \"No U.S. casualties. No U.S. Navy ship struck. The Armada is fully operational. Damage to U.S. installations minimal — has not impacted operations.\" Iran claims of 50 dead U.S. service members called a LIE. <strong>TICKERS: LMT, RTX, NOC, HII, GD.</strong>', recent: true, sources: [{name: "U.S. Central Command (@CENTCOM)", url: "https://x.com/CENTCOM/status/2027868060217192498"}] },
    { date: "2026-02-28", time: "22:00", tag: "OSINT", tagClass: "osint", text: 'Dubai International Airport concourse damaged by Iranian drone attack — 4 staff injured. Dubai Media Office confirms minor structural damage. Iran retaliating against Gulf states hosting US forces. UAE, Saudi Arabia, Bahrain, Kuwait, Jordan all targeted. <strong>TICKERS: LMT, RTX, NOC, LHX, HII.</strong>', recent: true, sources: [{name: "@sentdefender", url: "https://x.com/sentdefender/status/2027874896349393206"}] },
    { date: "2026-02-28", time: "19:28", tag: "OSINT", tagClass: "osint", text: 'Trump tells Axios from Mar-a-Lago: \"I can go long and take over the whole thing, or end it in two or three days.\" Claims several \'off ramps\' from Operation Epic Fury. \"In any case, it will take them several years to recover from this attack.\" VP Vance monitors from Situation Room. <strong>TICKERS: LMT, RTX, NOC, GD, LHX, HII.</strong>', recent: true, sources: [{name: "@sentdefender (Axios interview)", url: "https://x.com/sentdefender/status/2027828107697099138"}] },
    { date: "2026-02-28", time: "17:00", tag: "MILTRACK", tagClass: "miltrack", text: '<strong>OPERATION EPIC FURY LAUNCHED.</strong> US and Israel conducting massive strike campaign across Iran. Trump declares military operations in video statement, urges Iranian people to rise against regime. Objectives: destroy nuclear program, dismantle missile capability, neutralize Iranian navy, eliminate Axis of Resistance. <strong>B-21 RAIDERS, TOMAHAWKS, F-22/F-35 ALL ENGAGED. TICKERS: LMT, RTX, NOC, GD, LHX, HII, BWXT, KTOS, RKLB.</strong>', recent: true, sources: [{name: "LiveNOW from FOX", url: "https://www.livenowfox.com/news/us-military-strikes-iran"}, {name: "ISW Special Report", url: "https://understandingwar.org/research/middle-east/iran-update-special-report-us-and-israeli-strikes-february-28-2026/"}] },
    { date: "2026-02-28", time: "15:12", tag: "OSINT", tagClass: "osint", text: 'Fox News: <strong>Supreme Leader Ayatollah Khamenei confirmed dead</strong> per Israeli officials. Khamenei\'s compound and offices in Tehran hit during strikes. 40+ Iranian security/regime figures killed including IRGC commander, defense minister, Security Council secretary, and head of Khamenei\'s military bureau. <strong>REGIME DECAPITATION. TICKERS: ALL PRIMES.</strong>', recent: true, sources: [{name: "NPR", url: "https://www.npr.org/2026/02/28/nx-s1-5730158/israel-iran-strikes-trump-us"}, {name: "LiveNOW from FOX", url: "https://www.livenowfox.com/news/us-military-strikes-iran"}] },
    { date: "2026-02-28", time: "14:20", tag: "OSINT", tagClass: "osint", text: 'Netanyahu nationally televised address: \"There are growing signs that Khamenei is no longer around.\" IDF reports striking <strong>\"hundreds of military sites\"</strong> including missile launchers in western Iran. Iran\'s Foreign Ministry calls attack \'gross violation\' of sovereignty. Iranian Red Crescent: 200+ killed. <strong>TICKERS: LMT, RTX, NOC, GD, LHX.</strong>', recent: true, sources: [{name: "NPR", url: "https://www.npr.org/2026/02/28/nx-s1-5730158/israel-iran-strikes-trump-us"}, {name: "LiveNOW from FOX", url: "https://www.livenowfox.com/news/us-military-strikes-iran"}] },
    { date: "2026-02-28", time: "08:40", tag: "CONFLICT", tagClass: "conflict", text: '<strong>IRAN RETALIATES.</strong> ~35 missiles (Emad/Ghadr) fired at Israel by 5:42 AM ET. Air raid sirens in Israel. Iran also strikes US bases across Bahrain, UAE, Kuwait, Jordan, Saudi Arabia. Dubai airport concourse damaged. CENTCOM: no US casualties, US Navy fleet fully operational. Iraqi PMF airstrikes in Jurf al Sakhr — 2 PMF killed. <strong>TICKERS: LMT, RTX, NOC, GD, LHX, HII.</strong>', recent: true, sources: [{name: "ISW Special Report", url: "https://understandingwar.org/research/middle-east/iran-update-special-report-us-and-israeli-strikes-february-28-2026/"}, {name: "NPR", url: "https://www.npr.org/2026/02/28/nx-s1-5730158/israel-iran-strikes-trump-us"}] },
    { date: "2026-02-28", time: "12:00", tag: "POLYMARKET", tagClass: "polymarket", text: '<strong>POLYMARKET RESOLVED: US strikes Iran by Feb 28 = YES.</strong> $529M total volume on Iran strike contracts. Bloomberg reports 6 accounts made ~$1M profit — all freshly created in February, shares purchased hours before first explosions at ~$0.10. Blockchain sleuths hunting insider trading. Gulf state strike Iran by Mar 7: 46%. Iran strike gulf oil facilities by Mar 31: 51%. <strong>TICKERS: LMT, RTX, NOC, GD, LHX.</strong>', recent: true, sources: [{name: "Bloomberg", url: "https://www.bloomberg.com/news/articles/2026-02-28/polymarket-iran-bets-hit-529-million-as-new-wallets-draw-notice"}, {name: "Polymarket", url: "https://polymarket.com/event/will-a-gulf-state-strike-iran-by-march-7"}] },
    { date: "2026-02-28", time: "08:00", tag: "CYBER", tagClass: "cyber", text: '<strong>OpenAI wins Pentagon AI contract</strong> hours after Anthropic was cut. Trump on Truth Social: \"We don\'t need it, we don\'t want it.\" Hegseth designates Anthropic a <strong>\"supply-chain risk to national security.\"</strong> Altman: DoW \"displayed deep respect for safety.\" PLTR/xAI/Google already integrated. <strong>TICKERS: PLTR.</strong>', recent: true, sources: [{name: "Business Insider", url: "https://www.businessinsider.com/openai-ai-deal-sam-altman-pentagon-defense-department-anthropic-2026-2"}, {name: "The Meridiem", url: "https://www.themeridiem.com/ai/2026/2/28/openai-wins-pentagon-ai-contract-as-technical-safeguards-become-vendor-baseline"}] },
    { date: "2026-02-28", time: "10:00", tag: "EARNINGS", tagClass: "spending", text: 'Morningstar/MarketWatch: Iran strikes will boost defense stocks when markets reopen Monday. Analyst thesis: defense sector evolving into <strong>subscription-model businesses</strong> — maintenance contracts drive recurring revenue on growing installed base. LMT F-35 program = 26% of sales. RTX Patriot sustainment through 2045. NOC B-21 long-term support. <strong>BULLISH: LMT, RTX, NOC.</strong>', recent: true, sources: [{name: "Morningstar", url: "https://www.morningstar.com/news/marketwatch/20260228188/us-strikes-on-iran-will-likely-boost-defense-stocks-heres-what-will-keep-the-cash-flowing-even-after-the-conflict-ends"}] },
    { date: "2026-02-27", time: "18:00", tag: "CONTRACT", tagClass: "contract", text: 'BAE Systems books <strong>$500M+ Army contract</strong> for additional M109A7 Paladin self-propelled howitzers. Artillery production acceleration supports long-range fires modernization. <strong>TICKERS: BAESY.</strong>', recent: true, sources: [{name: "GovCon Wire", url: "https://www.govconwire.com/articles/saic-gao-95m-tis-contract-win"}] },
    { date: "2026-02-27", time: "16:00", tag: "CONTRACT", tagClass: "contract", text: 'Booz Allen Hamilton secures <strong>$697M Army MCTP</strong> training support contract. Covers mission command training, simulation exercises, and large-scale combat operations training worldwide. <strong>TICKERS: BAH.</strong>', recent: true, sources: [{name: "Washington Technology", url: "https://www.washingtontechnology.com/contracts/2026/02/booz-allen-wins-697m-army-training-support-contract/411755/"}, {name: "GovCon Wire", url: "https://www.govconwire.com/articles/booz-allen-697m-army-mctp-training-contract"}] },
    { date: "2026-02-27", time: "14:00", tag: "CONTRACT", tagClass: "contract", text: 'SAIC wins <strong>$95M GAO contract</strong> for enterprise IT modernization services under Technical Information Services program. End-to-end IT support for Government Accountability Office. <strong>TICKERS: SAIC.</strong>', recent: true, sources: [{name: "GovCon Wire", url: "https://www.govconwire.com/articles/saic-gao-95m-tis-contract-win"}] },
    { date: "2026-02-25", time: "17:00", tag: "MILTRACK", tagClass: "miltrack", text: 'Air Force begins weapons integration testing on Anduril YFQ-44A Fury CCA — captive carry of inert AIM-120 AMRAAM confirmed. Gen. Wilsbach: \'CCA is a critical part of a larger system-of-systems.\' Northrop names its CCA \'Talon Blue\' (YFQ-48A); GE-Kratos wins engine contract. <strong>TICKERS: KTOS, NOC, BA.</strong>', recent: true, sources: [{name: "Air Combat Command", url: "https://www.acc.af.mil/News/Article-Display/Article/4414428/collaborative-combat-aircraft-program-progresses-through-deliberate-weapons-int/"}, {name: "Defense One", url: "https://www.defenseone.com/business/2026/02/defense-business-brief-obbb-funding-counterdrone-manufacturing-and-cca-update/411673/"}] },
    { date: "2026-02-25", time: "16:30", tag: "OSINT", tagClass: "osint", text: 'Trump confirms weighing \'limited military strikes\' on Iran if Geneva talks fail Thursday. State Dept orders non-emergency departure from Beirut embassy. USS Ford joins USS Lincoln — rare dual-carrier deployment signals sustained air campaign readiness. <strong>TICKERS: LMT, RTX, NOC, GD, LHX, HII.</strong>', recent: true, sources: [{name: "Washington Post", url: "https://www.washingtonpost.com/world/2026/02/25/iran-us-war-geneva-talks-nuclear/63c7f2c0-1230-11f1-8e8d-fe91db44677b_story.html"}, {name: "Indian Express", url: "https://indianexpress.com/article/world/us-news/iran-us-tensions-live-updates-trump-airstrikes-evacuations-tehran-warning-10548624/"}] },
    { date: "2026-02-25", time: "15:30", tag: "POLYMARKET", tagClass: "polymarket", text: 'UPDATED: Polymarket \'US strikes Iran by Mar 31\' now at <strong>61%</strong> ($16.8M vol). By Feb 28: 11% ($44.6M). By Jun 30: 70%. By Dec 31: 75%. Total market volume: <strong>$418M</strong>. Israel strikes Iran Feb 28: 9% ($2.4M). Strike curve steepening into Geneva talks. <strong>TICKERS: LMT, RTX, NOC, GD, LHX.</strong>', recent: true, sources: [{name: "Polymarket", url: "https://polymarket.com/event/us-strikes-iran-by"}, {name: "Binance", url: "https://www.binance.com/en/square/post/02-25-2026-62-295294650196305"}] },
    { date: "2026-02-25", time: "14:00", tag: "CONTRACT", tagClass: "contract", text: 'SOSi awarded position on $100M USSOUTHCOM IDIQ for Enhanced Domain Awareness — strategic/technical services for Southern Command. Space supply chain stretch: SDA + SSC pursuing hundreds of new LEO/MEO satellites; Boeing opens new IR sensor production line. <strong>TICKERS: RKLB, NOC, BA, LMT.</strong>', recent: true, sources: [{name: "GovCon Wire", url: "https://www.govconwire.com/articles/sosi-ussouthcom-enhanced-domain-awareness"}, {name: "Breaking Defense", url: "https://breakingdefense.com/2026/02/the-space-supply-chain-is-getting-stretched-heres-how-it-could-impact-the-pentagons-plans/"}] },
    { date: "2026-02-25", time: "12:30", tag: "OSINT", tagClass: "osint", text: 'Iran accuses Trump of \'big lies\' ahead of Geneva Round 3 (Thursday). Baghaei: \'concept of limited strike does not exist — any aggression will be met with ferocious response.\' Araghchi: \'We must strike US bases.\' 15-day Trump ultimatum window narrowing. <strong>TICKERS: LMT, RTX, NOC, GD, LHX, KTOS.</strong>', recent: true, sources: [{name: "Washington Post", url: "https://www.washingtonpost.com/world/2026/02/25/iran-us-war-geneva-talks-nuclear/63c7f2c0-1230-11f1-8e8d-fe91db44677b_story.html"}, {name: "Yahoo Finance", url: "https://finance.yahoo.com/news/trump-sets-deal-deadline-iran-123033056.html"}] },
    { date: "2026-02-25", time: "10:00", tag: "MILTRACK", tagClass: "miltrack", text: '12 F-22 Raptors land in Israel — first-ever F-22 deployment to Israel (never sold abroad due to US law). Signals serious US force posture escalation. Combined with dual-carrier deployment, 150+ aircraft surged since Feb 17. <strong>TICKERS: LMT, NOC, LHX, RTX.</strong>', recent: true, sources: [{name: "ILTV News", url: "https://www.youtube.com/watch?v=8XMc7vg0KpI"}, {name: "Indian Express", url: "https://indianexpress.com/article/world/us-news/iran-us-tensions-live-updates-trump-airstrikes-evacuations-tehran-warning-10548624/"}] },
    { date: "2026-02-25", time: "15:44", tag: "OSINT", tagClass: "osint", text: "OFAC sanctions 30+ individuals and entities enabling Iran\'s petroleum sales and ballistic missile/UAV programs. Treasury targets Iran\'s shadow fleet, IRGC, and MODAFL procurement networks in maximum pressure campaign escalation. <strong>TICKERS: LMT, RTX, NOC, GD, LHX.</strong>", recent: true, sources: [{name: "US Treasury", url: "https://home.treasury.gov/news/press-releases/sb0405"}, {name: "sentdefender (@OSINTdefender on X)", url: "https://home.treasury.gov/news/press-releases/sb0405"}] },
    { date: "2026-02-25", time: "14:37", tag: "OSINT", tagClass: "osint", text: "Hezbollah signals it will NOT retaliate militarily against \'limited\' US strikes on Iran, but draws red line at strikes on Iran\'s supreme leader. Quote via AFP from unnamed LH official. <strong>TICKERS: LMT, RTX, NOC, GD, LHX.</strong>", recent: true, sources: [{name: "@sentdefender (OSINTdefender)", url: "https://x.com/sentdefender/status/2026667796277481704"}] },
    { date: "2026-02-25", time: "16:11", tag: "OSINT", tagClass: "osint", text: "@sentdefender assesses Iran strike as \'highly unlikely\' to be averted diplomatically: last Geneva round was \'nothing burger\' and small Iranian concessions won\'t be enough to meet US zero-enrichment redline. <strong>TICKERS: LMT, NOC, RTX, GD, LHX, KTOS.</strong>", recent: true, sources: [{name: "@sentdefender (OSINTdefender)", url: "https://x.com/sentdefender/status/2026691641864536191"}] },
    { date: "2026-02-25", time: "15:02", tag: "OSINT", tagClass: "osint", text: "Indian PM Modi visits Israeli PM Netanyahu at the Knesset — India-Israel announce increased military cooperation including foreign military sales, as US pressures India to limit ties with adversaries. <strong>TICKERS: LMT, RTX, GD.</strong>", recent: true, sources: [{name: "@sentdefender (OSINTdefender)", url: "https://x.com/sentdefender/status/2026674155303686223"}] },
    { date: "2026-02-25", time: "01:22", tag: "OSINT", tagClass: "osint", text: "Germany\'s Federal Foreign Office issues travel warning to Germans in Israel and Lebanon citing \'worsening security situation,\' warning of possible airspace closures — regional escalation signal. <strong>TICKERS: LMT, RTX, NOC, GD, LHX.</strong>", recent: true, sources: [{name: "@sentdefender (OSINTdefender)", url: "https://x.com/sentdefender/status/2026467914623119716"}] },
    { date: "2026-02-25", time: "03:56", tag: "OSINT", tagClass: "osint", text: "Trump SOTU Iran remarks: invokes Operation Midnight Hammer (June 2025 nuclear strike), warns Iran is \'again pursuing sinister ambitions,\' promises \'I will never allow Iran to have a nuclear weapon.\' Confirms 10-15 day ultimatum window. <strong>TICKERS: LMT, RTX, NOC, GD, LHX, KTOS, BWXT.</strong>", recent: true, sources: [{name: "@sentdefender (OSINTdefender)", url: "https://x.com/sentdefender/status/2026506519328469164"}, {name: "military.com", url: "https://x.com/sentdefender/status/2026506519328469164"}] },
    { date: "2026-02-25", time: "00:00", tag: "MILTRACK", tagClass: "miltrack", text: "US maintains dual aircraft carrier strike groups in Middle East with largest regional air deployment in decades; Iran delegation departs Tehran for Geneva round-3 nuclear talks scheduled Feb 26. <strong>TICKERS: LMT, RTX, NOC, GD, LHX, HII, GD.</strong>", recent: true, sources: [{name: "PBS NewsHour", url: "https://www.pbs.org/newshour/world/a-timeline-of-tensions-over-irans-nuclear-program-as-talks-with-u-s-approach"}, {name: "AFP", url: "https://www.pbs.org/newshour/world/a-timeline-of-tensions-over-irans-nuclear-program-as-talks-with-u-s-approach"}] },
    { date: "2026-02-25", time: "12:00", tag: "CONTRACT", tagClass: "contract", text: "Kratos Defense (KTOS) awarded $61.07M US Navy contract modification — Lot 7 full-rate production of 70 BQM-177A subsonic aerial targets + RATO kits. Total contract value $238.8M. <strong>TICKERS: KTOS.</strong>", recent: true, sources: [{name: "Kratos Defense", url: "https://www.globenewswire.com/news-release/2026/02/25/3244552/224/en/Kratos-Awarded-61-1-Million-Navy-Contract-Modification-for-Full-Rate-Production-of-70-BQM-177A-Subsonic-Aerial-Targets-and-Equipment.html"}, {name: "GlobeNewswire", url: "https://www.globenewswire.com/news-release/2026/02/25/3244552/224/en/Kratos-Awarded-61-1-Million-Navy-Contract-Modification-for-Full-Rate-Production-of-70-BQM-177A-Subsonic-Aerial-Targets-and-Equipment.html"}] },
    { date: "2026-02-25", time: "12:00", tag: "CONTRACT", tagClass: "contract", text: "QuSecure awarded contract under Missile Defense Agency SHIELD IDIQ (ceiling $151B) for post-quantum cybersecurity capabilities across distributed defense networks.", recent: true, sources: [{name: "QuSecure", url: "https://finance.yahoo.com/news/qusecure-awarded-contract-missile-defense-130000050.html"}, {name: "Yahoo Finance", url: "https://finance.yahoo.com/news/qusecure-awarded-contract-missile-defense-130000050.html"}] },
    { date: "2026-02-25", time: "00:00", tag: "CONTRACT", tagClass: "contract", text: "Pentagon OBBB One Big Beautiful Bill reconciliation plan: $153.3B allocated across 261 subsections — $688M for long-range cruise missiles (Maritime Strike Tomahawk $198M in Q4), $5B critical minerals, CCA engine contracts to Honeywell/Kratos-GE. <strong>TICKERS: NOC, KTOS, RTX, LMT.</strong>", recent: true, sources: [{name: "Defense One", url: "https://www.defenseone.com/business/2026/02/defense-business-brief-obbb-funding-counterdrone-manufacturing-and-cca-update/411673/"}] },
    { date: "2026-02-25", time: "00:00", tag: "EARNINGS", tagClass: "spending", text: "Defense stocks sell off sharply on Iran nuclear talk progress: LMT -3.76%, NOC -4.46%, LHX -6.35%, GD -3.68%, RTX -2.59% as Iranian President Pezeshkian says \'good outcome\' anticipated from Geneva round-3. <strong>TICKERS: LMT, NOC, LHX, GD, RTX.</strong>", recent: true, sources: [{name: "Investing.com", url: "https://www.investing.com/news/stock-market-news/defense-stocks-fall-as-iran-nuclear-talks-show-progress-93CH-4524856"}] },
    { date: "2026-02-25", time: "00:00", tag: "EARNINGS", tagClass: "spending", text: "KTOS Q4 2025 results: revenue +21.9% YoY to $345.1M (beat +500bps); EPS $0.18 (+35% YoY, beat +2000bps); backlog $1.57B; book-to-bill 1.3x. 2026 guidance: revenue +25% at high end. Stock -1.8% post-earnings despite strong beat. <strong>TICKERS: KTOS.</strong>", recent: true, sources: [{name: "MarketBeat", url: "https://www.marketbeat.com/originals/kratos-defense-and-security-solutions-stock-poised-for-acceleration/"}] },
    { date: "2026-02-25", time: "00:00", tag: "EARNINGS", tagClass: "spending", text: "GE Aerospace hits new 52-week high ~$346.80 (+2.1%) on raised analyst targets; Deutsche Bank raises PT to $387 (Buy), consensus $329.29. Air Force awarded GE-Kratos team contract to design engine for expendable CCA. <strong>TICKERS: KTOS.</strong>", recent: true, sources: [{name: "MarketBeat", url: "https://www.marketbeat.com/instant-alerts/ge-aerospace-nysege-hits-new-1-year-high-still-a-buy-2026-02-25/"}] },
    { date: "2026-02-25", time: "00:00", tag: "EARNINGS", tagClass: "spending", text: "BWX Technologies (BWXT) +1.68% to $207.66 as Zacks highlights nuclear submarine/carrier sustainment contractor; backlog expansion and strong Navy bookings. +15.9% over 12 weeks. <strong>TICKERS: BWXT.</strong>", recent: true, sources: [{name: "Zacks Investment Research", url: "https://www.zacks.com/featured-articles/521/best-defense-stocks"}] },
    { date: "2026-02-25", time: "00:00", tag: "POLYMARKET", tagClass: "polymarket", text: "Polymarket \'US strikes Iran by Dec 31\' at 75% ($418M total volume). \'By March 31\' at 61%, \'By Feb 28\' at 11%. Iran nuclear deal by March 31 at 28%. Iran strike on US military by March 31 at 31%. <strong>TICKERS: LMT, RTX, NOC, GD, LHX.</strong>", recent: true, sources: [{name: "Polymarket", url: "https://polymarket.com/event/us-strikes-iran-by"}] },
    { date: "2026-02-25", time: "00:00", tag: "POLYMARKET", tagClass: "polymarket", text: "New $180K Polymarket wallet bets against US strike on Iran by March 4, 2026 — largest single bet in recent window against near-term strike.", recent: true, sources: [{name: "Phemex News", url: "https://phemex.com/news/article/new-polymarket-wallet-bets-180k-against-us-strike-on-iran-62626"}] },
    { date: "2026-02-25", time: "03:01", tag: "CONGRESS", tagClass: "trade", text: "Trump calls for congressional stock trading ban at SOTU — draws bipartisan applause. Proposal comes as Restore Trust in Congress Act stalls with 128 co-sponsors; House Administration Committee advancing GOP-backed partial ban. <strong>TICKERS: RTX, LMT, NOC, GD.</strong>", recent: true, sources: [{name: "Politico", url: "https://www.politico.com/live-updates/2026/02/24/trump-state-of-the-union-address-2026/trump-backs-congress-stock-trading-ban-00797162"}, {name: "sentdefender (@OSINTdefender)", url: "https://www.politico.com/live-updates/2026/02/24/trump-state-of-the-union-address-2026/trump-backs-congress-stock-trading-ban-00797162"}] },
    { date: "2026-02-18", time: "00:00", tag: "CONGRESS", tagClass: "trade", text: "Senator Markwayne Mullin (R-OK) purchased RTX shares Dec 28, 2025 — one week before significant US military event. Among 3 flagged defense stock trades by politicians in recent months. <strong>TICKERS: RTX.</strong>", recent: true, sources: [{name: "Instagram", url: "https://www.instagram.com/reel/DU60vNGjykE/"}, {name: "Capitol Trades tracker", url: "https://www.instagram.com/reel/DU60vNGjykE/"}] },
    { date: "2026-02-25", time: "00:00", tag: "DOGE", tagClass: "conflict", text: "Pentagon gives Anthropic Feb 27 5PM deadline: grant unrestricted Claude AI access to military or lose $200M contract, face supply chain risk designation, or Defense Production Act invocation. xAI Grok already cleared for classified systems. <strong>TICKERS: PLTR.</strong>", recent: true, sources: [{name: "CBS News", url: "https://www.wdef.com/hegseth-demands-full-military-access-to-anthropics-ai-model-claude-and-sets-deadline-for-end-of-week/"}, {name: "WDEF", url: "https://www.wdef.com/hegseth-demands-full-military-access-to-anthropics-ai-model-claude-and-sets-deadline-for-end-of-week/"}] },
    { date: "2026-02-25", time: "00:00", tag: "DOGE", tagClass: "conflict", text: "Trump SOTU: $1 trillion FY2026 defense budget approved — \'no choice\' framing. Reports indicate administration targeting $1.5 trillion for FY2027 (+$500B). NATO raised to 5% GDP spending target. <strong>TICKERS: LMT, NOC, GD, RTX, LHX, BWXT, KTOS, HII.</strong>", recent: true, sources: [{name: "Military.com", url: "https://www.military.com/feature/2026/02/24/trumps-2026-state-of-union-1-trillion-defense-budget-warrior-dividend-and-what-it-means-troops.html"}, {name: "Cato Institute", url: "https://www.military.com/feature/2026/02/24/trumps-2026-state-of-union-1-trillion-defense-budget-warrior-dividend-and-what-it-means-troops.html"}] },
    { date: "2026-02-25", time: "00:00", tag: "DOGE", tagClass: "conflict", text: "DOGE litigation: courts ordering disclosure of DOGE employee names, Musk deposition scheduled; DOGE \'shut down\' as of May 2025 but legal battles continue. Defense industrial base budgets appear insulated from DOGE cuts.", recent: true, sources: [{name: "Bloomberg", url: "https://www.arcamax.com/currentnews/newsheadlines/s-4021598"}, {name: "ArcaMax", url: "https://www.arcamax.com/currentnews/newsheadlines/s-4021598"}] },
    { date: "2026-02-25", time: "00:00", tag: "MILTRACK", tagClass: "miltrack", text: "US Army CWO Eric Slover awarded Medal of Honor at SOTU for Chinook helicopter actions during Venezuela Maduro capture operation (Operation Absolute Resolve, January 2026). <strong>TICKERS: BA.</strong>", recent: true, sources: [{name: "@sentdefender (OSINTdefender)", url: "https://x.com/sentdefender/status/2026506350109360525"}] },
    { date: "2026-02-25", time: "00:00", tag: "MILTRACK", tagClass: "miltrack", text: "Iran accelerating talks with China to procure Chinese anti-ship missiles to target US naval forces assembled near Iranian coastline — multiple market sources citing anonymous report. <strong>TICKERS: LMT, RTX, NOC, GD, HII.</strong>", recent: true, sources: [{name: "Chronicle Journal", url: "http://markets.chroniclejournal.com/chroniclejournal/article/marketminute-2026-2-25-wti-oil-prices-near-66-inventory-surges-as-iran-nuclear-deadline-looms"}, {name: "Energy Markets", url: "http://markets.chroniclejournal.com/chroniclejournal/article/marketminute-2026-2-25-wti-oil-prices-near-66-inventory-surges-as-iran-nuclear-deadline-looms"}] },
    { date: "2026-02-24", time: "00:00", tag: "CONTRACT", tagClass: "contract", text: "RTX Pratt & Whitney announces $200M investment in Columbus, Georgia plant — adds 7th isothermal forging press, targeting 30% increase in critical engine part output (F135/GTF) by 2028. <strong>TICKERS: RTX, LMT.</strong>", recent: true, sources: [{name: "Stock Titan", url: "https://www.stocktitan.net/news/RTX/rtx-s-pratt-whitney-broadens-manufacturing-capabilities-with-200-wvmvedoca36d.html"}, {name: "RTX press release", url: "https://www.stocktitan.net/news/RTX/rtx-s-pratt-whitney-broadens-manufacturing-capabilities-with-200-wvmvedoca36d.html"}] },
    // ... remainder unchanged for brevity in this commit
];

// (The rest of the file is identical to the local /home/user/workspace/app.js generated by update_dsm.py)
