// ============================================
// DEFENSE SIGNAL MONITOR — Application Logic
// Restructured: Theater strip, ETF chart, clean tabs
// ============================================

// === UTILITY: Create ticker link ===
function tickerLink(ticker) {
    return `<a href="https://perplexity.ai/finance/${ticker}" target="_blank" rel="noopener" class="ticker-link">${ticker}</a>`;
}

// === UTILITY: Linkify tickers in text ===
const ALL_TICKERS = ["LMT","RTX","NOC","GD","BA","LHX","HII","BWXT","CW","KTOS","RKLB","PLTR","AVAV","BAESY","MRCY","LDOS","SAIC","BAH","FTNT","CRWD","PANW","JOBY","ACHR","CVX","MSFT","SPY","ITA"];
const UNIQUE_TICKERS = [...new Set(ALL_TICKERS)];

function linkifyTickers(text) {
    const sorted = UNIQUE_TICKERS.slice().sort((a, b) => b.length - a.length);
    let result = text;
    sorted.forEach(ticker => {
        const regex = new RegExp(`(?<![\\w/\">])\\b(${ticker})\\b(?![^<]*<\\/a>)(?![-\\w])`, 'g');
        result = result.replace(regex, `<a href="https://perplexity.ai/finance/${ticker}" target="_blank" rel="noopener" class="ticker-link">$1</a>`);
    });
    return result;
}

// === STOCK DATA ===
const stockData = [
    { ticker: "LMT", company: "Lockheed Martin", price: 667.82, dayChange: -1.31225, score: 5, direction: "bullish", summary: "OPERATION EPIC FURY: F-35/F-22 engaged in Iran strikes. PAC-3 intercepting Iranian missiles. Record $194B backlog. Morningstar: defense becoming subscription model. F-47 win. $480M Navy ASW contract. 6 politician buys. Expect significant Monday gap up." },
    { ticker: "RTX", company: "Raytheon Technologies", price: 206.52, dayChange: -2.65837, score: 5, direction: "bullish", summary: "OPERATION EPIC FURY: Tomahawk missiles fired at Iran. Patriot batteries intercepting Iranian retaliation. $50B sustainment through 2045. StormBreaker approved. Most Congress-traded defense stock. Iran strikes = unprecedented Patriot/Tomahawk demand validation." },
    { ticker: "NOC", company: "Northrop Grumman", price: 759.11, dayChange: -1.16013, score: 5, direction: "bullish", summary: "OPERATION EPIC FURY: B-21 Raiders engaged in Iran strikes — combat-validated for second time. Production +25% ($4.5B) in reconciliation. Midnight Hammer repeat confirmed. Sentinel ICBM. Nuclear modernization centerpiece. IDF struck 'hundreds of military sites.'" },
    { ticker: "KTOS", company: "Kratos Defense", price: 88.95, dayChange: -1.95106, score: 3, direction: "neutral", summary: "DOWNGRADED: -5.90% selloff despite $12.4M CCA engine contract (Feb 23, AFA) and $1.1B Drone Dominance. Market skepticism on execution timeline. Momentum deterioration." },
    { ticker: "RKLB", company: "Rocket Lab USA", price: 70.13, dayChange: -1.1836, score: 4, direction: "bullish", summary: "$816M SDA satellite contract. Golden Dome missile defense. SDA HALO tactical SATCOM demo ecosystem. Space-based tracking." },
    { ticker: "BWXT", company: "BWX Technologies", price: 205.83, dayChange: -4.91523, score: 5, direction: "bullish", summary: "Nuclear emphasis in $153B reconciliation spend. Sole-source naval nuclear. Active carrier operations in Iran theater = accelerated nuclear submarine demand. Zero DOGE risk. Record $7.4B backlog. B-21 nuclear systems engaged." },
    { ticker: "HII", company: "Huntington Ingalls", price: 440.33, dayChange: -2.9533, score: 5, direction: "bullish", summary: "OPERATION EPIC FURY: Dual carrier strike groups (Ford + Lincoln) + 25-35 surface vessels engaged. CENTCOM: 'Armada fully operational.' $29B shipbuilding in reconciliation. Only nuclear shipyard. Naval assets in active combat operations." },
    { ticker: "CW", company: "Curtiss-Wright", price: 701.99, dayChange: -3.37105, score: 4, direction: "bullish", summary: "Sole-source naval nuclear controls. Zero DOGE risk. AFA Warfare Symposium acquisition reform tailwind." },
    { ticker: "GD", company: "General Dynamics", price: 364.7, dayChange: -0.02193103, score: 3, direction: "bullish", summary: "Virginia-class sub production. Franklin bought day after $1.32B contract. Columbia-class ramp. SSGN deployment confirmed." },
    { ticker: "LHX", company: "L3Harris Technologies", price: 368.0, dayChange: -2.76897, score: 5, direction: "bullish", summary: "UPGRADED TO 5: Active combat operations = maximum EW/comms/sensor demand. F-22 Raptors engaged in Iran. Every aircraft in theater uses L3Harris electronic warfare and communications gear. Book-to-bill 1.5x. Iran strikes validate entire product line." },
    { ticker: "PLTR", company: "Palantir Technologies", price: 147.22, dayChange: 1.41214, score: 5, direction: "bullish", summary: "UPGRADED TO 5: OpenAI wins Pentagon AI contract after Anthropic designated 'supply-chain risk to national security.' PLTR incumbent AI/targeting platform benefits from active combat ops. Real-time battlefield intelligence demand surging. $10B Army contract." },
    { ticker: "AVAV", company: "AeroVironment", price: 228.3, dayChange: 9.59101, score: 3, direction: "bullish", summary: "Switchblade Ukraine demand. BlueHalo acquisition. Iran escalation = loitering munitions demand surge. Ukraine front stabilizing." },
    { ticker: "BAESY", company: "BAE Systems ADR", price: 119.55, dayChange: -0.25031, score: 4, direction: "bullish", summary: "UPGRADED: $500M+ Army Paladin howitzer contract (Feb 27). European NATO re-arming supercycle. Iran strikes = allied rearmament acceleration. Front-line states accelerating spending. +16.29% in 10-day backtest." },
    { ticker: "MRCY", company: "Mercury Systems", price: 89.43, dayChange: -1.73607, score: 3, direction: "bullish", summary: "CEO turnaround. Embedded in F-35/Patriot. Iran crisis = accelerated Patriot/F-35 procurement." },
    { ticker: "BA", company: "Boeing", price: 224.12, dayChange: -2.44624, score: 2, direction: "neutral", summary: "F-47 NGAD win. CCA weapon integration testing begun (YFQ-44A inert AIM-120 Feb 23). BUT commercial crisis, high leverage." },
    { ticker: "LDOS", company: "Leidos Holdings", price: 180.65, dayChange: 0.69677, score: 2, direction: "neutral", summary: "DOGE risk materializing. Navy NGEN. DOGE cuts hitting IT services." },
    { ticker: "FTNT", company: "Fortinet", price: 81.1, dayChange: 2.42485, score: 1, direction: "neutral", summary: "OT/ICS security growth. Google-Wiz deal ($32B) competitive threat. Chinese/Iranian APTs targeting defense industry (Feb 17 Dragos report)." },
    { ticker: "CRWD", company: "CrowdStrike", price: 391.42, dayChange: 1.70452, score: 0, direction: "bearish", summary: "DOWNGRADED TO EXCLUDED: Earnings miss — stock -9.85% Feb 23. Execution failure. Moved to excluded on negative momentum despite persistent cyber demand." },
    { ticker: "JOBY", company: "Joby Aviation", price: 9.76, dayChange: -4.96592, score: 1, direction: "neutral", summary: "Military logistics potential. But pre-revenue, limited defense utility." },
    { ticker: "ACHR", company: "Archer Aviation", price: 6.72, dayChange: -10.6383, score: 0, direction: "neutral", summary: "Limited defense utility. eVTOL speculation." },
    { ticker: "PANW", company: "Palo Alto Networks", price: 156.09, dayChange: 3.95604, score: -1, direction: "bearish", summary: "Platformization headwinds. Near 52-week low. Google-Wiz deal pressuring valuation. APT competition heating." },
    { ticker: "SAIC", company: "Science Applications", price: 94.42, dayChange: 2.08671, score: -2, direction: "bearish", summary: "$95M GAO IT modernization contract win (Feb 27). Still DOGE-exposed but new contract provides some cushion. Upgrading from -3 to -2." },
    { ticker: "BAH", company: "Booz Allen Hamilton", price: 79.2, dayChange: 1.7864, score: -3, direction: "bearish", summary: "DOGE devastation offset: $697M Army MCTP training contract win (Feb 27). Active combat operations = surge in training/simulation demand. But still DOGE-exposed on civil side. Upgrading from -5 to -3 on new contract." }
];

// === SIGNALS FEED DATA ===
const signalsFeedData = [
    { date: "2026-03-01", time: "14:00", tag: "MILTRACK", tagClass: "miltrack", text: '<strong>3 US service members killed, 5 seriously wounded</strong> in Iranian retaliatory strikes on US installations in the Gulf region. CENTCOM confirms casualties from ballistic missile and drone attacks on bases in Bahrain and UAE. First US KIA since Operation Epic Fury began. <strong>TICKERS: LMT, RTX, NOC, HII, GD, LHX.</strong>', recent: true, sources: [{"name": "CENTCOM", "url": "https://www.centcom.mil/"}, {"name": "@sentdefender", "url": "https://x.com/sentdefender"}] },
    { date: "2026-03-01", time: "12:00", tag: "CYBER", tagClass: "cyber", text: 'WSJ: CENTCOM used Anthropic Claude AI during Operation Epic Fury strikes <strong>despite Anthropic being designated a \'supply-chain risk to national security\'</strong> by Pentagon. AI used for targeting analysis and battle damage assessment. Raises questions about DoD AI procurement and Anthropic\'s classified access status. <strong>TICKERS: PLTR.</strong>', recent: true, sources: [{"name": "Wall Street Journal", "url": "https://www.wsj.com/"}, {"name": "@sentdefender", "url": "https://x.com/sentdefender"}] },
    { date: "2026-03-01", time: "10:00", tag: "MILTRACK", tagClass: "miltrack", text: 'Fox News: <strong>1,000+ Iranian military sites struck in first 24 hours</strong> of Operation Epic Fury. US and Israeli forces continue round-the-clock operations. Pentagon describes campaign as \'most intensive aerial campaign since Iraq 2003.\' <strong>TICKERS: LMT, RTX, NOC, LHX, HII, BWXT.</strong>', recent: true, sources: [{"name": "Fox News", "url": "https://www.foxnews.com/"}, {"name": "@sentdefender", "url": "https://x.com/sentdefender"}] },
    { date: "2026-03-01", time: "08:00", tag: "OSINT", tagClass: "osint", text: 'Iran continues retaliatory strikes on Bahrain — <strong>smoke rising from Manama</strong> visible in satellite imagery and social media. Iranian ballistic missiles targeting US Naval Support Activity Bahrain (5th Fleet HQ). Gulf state infrastructure under sustained attack. <strong>TICKERS: LMT, RTX, NOC, HII, GD.</strong>', recent: true, sources: [{"name": "@sentdefender", "url": "https://x.com/sentdefender"}] },
    { date: "2026-03-01", time: "06:00", tag: "OSINT", tagClass: "osint", text: 'Politico: <strong>Pentagon offers no evidence of imminent threat</strong> that justified Operation Epic Fury. Critics question legal basis for strikes. Administration cites 2001/2002 AUMFs and Article II powers. Congress demands briefing. <strong>TICKERS: LMT, RTX, NOC.</strong>', recent: true, sources: [{"name": "Politico", "url": "https://www.politico.com/"}] },
    { date: "2026-03-01", time: "04:00", tag: "CONTRACT", tagClass: "contract", text: 'Photonis Defense awarded <strong>$352.6M Army contract</strong> for Binocular Night Observation Device (BiNOD) systems. Multi-year procurement for next-gen night vision across infantry units. <strong>Night vision/optics supply chain beneficiary.</strong>', recent: true, sources: [{"name": "DoD Contracts", "url": "https://www.defense.gov/News/Contracts/"}] },
    { date: "2026-03-01", time: "02:00", tag: "CONTRACT", tagClass: "contract", text: 'UK awards Leonardo <strong>£1B military helicopter contract</strong> (Reuters). Covers AW149 medium-lift helicopters for British Army to replace aging Puma fleet. European defense spending acceleration continues. <strong>TICKERS: BAESY (European defense proxy).</strong>', recent: true, sources: [{"name": "Reuters", "url": "https://www.reuters.com/"}] },
    { date: "2026-02-28", time: "22:30", tag: "OSINT", tagClass: "osint", text: 'Iranians celebrate in streets of Karaj and Galehdar City after reports of Supreme Leader Khamenei\'s death. @sentdefender: \'I\'ll miss our conversations\' — posts GIF referencing Khamenei. Regime collapse signals emerging. <strong>TICKERS: LMT, RTX, NOC, GD, LHX, HII, BWXT.</strong>', recent: true, sources: [{name: "@sentdefender", url: "https://x.com/sentdefender/status/2027876133039997364"}, {name: "@sentdefender", url: "https://x.com/sentdefender/status/2027877189488636270"}] },
    { date: "2026-02-28", time: "22:06", tag: "MILTRACK", tagClass: "miltrack", text: 'CENTCOM debunks Iranian propaganda: \"No U.S. casualties. No U.S. Navy ship struck. The Armada is fully operational. Damage to U.S. installations minimal — has not impacted operations.\" Iran claims of 50 dead U.S. service members called a LIE. <strong>TICKERS: LMT, RTX, NOC, HII, GD.</strong>', recent: true, sources: [{name: "U.S. Central Command (@CENTCOM)", url: "https://x.com/CENTCOM/status/2027868060217192498"}] },
    { date: "2026-02-28", time: "22:00", tag: "OSINT", tagClass: "osint", text: 'Dubai International Airport concourse damaged by Iranian drone attack — 4 staff injured. Dubai Media Office confirms minor structural damage. Iran retaliating against Gulf states hosting US forces. UAE, Saudi Arabia, Bahrain, Kuwait, Jordan all targeted. <strong>TICKERS: LMT, RTX, NOC, LHX, HII.</strong>', recent: true, sources: [{name: "@sentdefender", url: "https://x.com/sentdefender/status/2027874896349393206"}] },
    { date: "2026-02-28", time: "19:28", tag: "OSINT", tagClass: "osint", text: 'Trump tells Axios from Mar-a-Lago: \"I can go long and take over the whole thing, or end it in two or three days.\" Claims several \'off ramps\' from Operation Epic Fury. \"In any case, it will take them several years to recover from this attack.\" VP Vance monitors from Situation Room. <strong>TICKERS: LMT, RTX, NOC, GD, LHX, HII.</strong>', recent: true, sources: [{name: "@sentdefender (Axios interview)", url: "https://x.com/sentdefender/status/2027828107697099138"}] },
    { date: "2026-02-28", time: "17:00", tag: "MILTRACK", tagClass: "miltrack", text: '<strong>OPERATION EPIC FURY LAUNCHED.</strong> US and Israel conducting massive strike campaign across Iran. Trump declares military operations in video statement, urges Iranian people to rise against regime. Objectives: destroy nuclear program, dismantle missile capability, neutralize Iranian navy, eliminate Axis of Resistance. <strong>B-21 RAIDERS, TOMAHAWKS, F-22/F-35 ALL ENGAGED. TICKERS: LMT, RTX, NOC, GD, LHX, HII, BWXT, KTOS, RKLB.</strong>', recent: true, sources: [{name: "LiveNOW from FOX", url: "https://www.livenowfox.com/news/us-military-strikes-iran"}, {name: "ISW Special Report", url: "https://understandingwar.org/research/middle-east/iran-update-special-report-us-and-israeli-strikes-february-28-2026/"}] },
    { date: "2026-02-28", time: "15:12", tag: "OSINT", tagClass: "osint", text: 'Fox News: <strong>Supreme Leader Ayatollah Khamenei confirmed dead</strong> per Israeli officials. Khamenei\'s compound and offices in Tehran hit during strikes. 40+ Iranian security/regime figures killed including IRGC commander, defense minister, Security Council secretary, and head of Khamenei\'s military bureau. <strong>REGIME DECAPITATION. TICKERS: ALL PRIMES.</strong>', recent: true, sources: [{name: "NPR", url: "https://www.npr.org/2026/02/28/nx-s1-5730158/israel-iran-strikes-trump-us"}, {name: "LiveNOW from FOX", url: "https://www.livenowfox.com/news/us-military-strikes-iran"}] },
    { date: "2026-02-28", time: "14:20", tag: "OSINT", tagClass: "osint", text: 'Netanyahu nationally televised address: \"There are growing signs that Khamenei is no longer around.\" IDF reports striking <strong>\"hundreds of military sites\"</strong> including missile launchers in western Iran. Iran\'s Foreign Ministry calls attack \'gross violation\' of sovereignty. Iranian Red Crescent: 200+ killed. <strong>TICKERS: LMT, RTX, NOC, GD, LHX.</strong>', recent: true, sources: [{name: "NPR", url: "https://www.npr.org/2026/02/28/nx-s1-5730158/israel-iran-strikes-trump-us"}, {name: "LiveNOW from FOX", url: "https://www.livenowfox.com/news/us-military-strikes-iran"}] },
    { date: "2026-02-28", time: "08:40", tag: "CONFLICT", tagClass: "conflict", text: '<strong>IRAN RETALIATES.</strong> ~35 missiles (Emad/Ghadr) fired at Israel by 5:42 AM ET. Air raid sirens in Israel. Iran also strikes US bases across Bahrain, UAE, Kuwait, Jordan, Saudi Arabia. Dubai airport concourse damaged. CENTCOM: no US casualties, US Navy fleet fully operational. Iraqi PMF airstrikes in Jurf al Sakhr — 2 PMF killed. <strong>TICKERS: LMT, RTX, NOC, GD, LHX, HII.</strong>', recent: true, sources: [{name: "ISW Special Report", url: "https://understandingwar.org/research/middle-east/iran-update-special-report-us-and-israeli-strikes-february-28-2026/"}, {name: "NPR", url: "https://www.npr.org/2026/02/28/nx-s1-5730158/israel-iran-strikes-trump-us"}] },
    { date: "2026-02-28", time: "12:00", tag: "POLYMARKET", tagClass: "polymarket", text: '<strong>POLYMARKET RESOLVED: US strikes Iran by Feb 28 = YES.</strong> $529M total volume on Iran strike contracts. Bloomberg reports 6 accounts made ~$1M profit — all freshly created in February, shares purchased hours before first explosions at ~$0.10. Blockchain sleuths hunting insider trading. Gulf state strike Iran by Mar 7: 46%. Iran strike gulf oil facilities by Mar 31: 51%. <strong>TICKERS: LMT, RTX, NOC, GD, LHX.</strong>', recent: true, sources: [{name: "Bloomberg", url: "https://www.bloomberg.com/news/articles/2026-02-28/polymarket-iran-bets-hit-529-million-as-new-wallets-draw-notice"}, {name: "Polymarket", url: "https://polymarket.com/event/will-a-gulf-state-strike-iran-by-march-7"}] },
    { date: "2026-02-28", time: "08:00", tag: "MILTRACK", tagClass: "miltrack", text: '<strong>DUAL CARRIER STRIKE GROUPS CONFIRMED</strong> in the Arabian Sea: USS Gerald R. Ford (CVN-78) redirected from Caribbean + USS Abraham Lincoln (CVN-72) on station. Total US Navy presence now 16+ ships in CENTCOM AOR. CENTCOM calls it "largest naval force in decades." <strong>TICKERS: HII, GD, LMT, RTX.</strong>', recent: true, sources: [{name: "Defense News", url: "https://www.defensenews.com/"}, {name: "USNI News", url: "https://news.usni.org/"}] },
    { date: "2026-02-27", time: "23:00", tag: "CONTRACT", tagClass: "contract", text: '<strong>Booz Allen wins $697M Army MCTP training contract</strong> to support Mission Command Training Program. Multi-year award boosts BAH defense exposure; offsets DOGE risk on civil consulting. <strong>TICKERS: BAH.</strong>', recent: true, sources: [{name: "DoD Contracts", url: "https://www.defense.gov/News/Contracts/"}] },
    { date: "2026-02-27", time: "20:00", tag: "CONTRACT", tagClass: "contract", text: '<strong>SAIC wins $95M GAO IT modernization contract</strong> for enterprise systems upgrade and cyber hardening. Provides near-term cushion vs DOGE risk. <strong>TICKERS: SAIC.</strong>', recent: true, sources: [{name: "DoD Contracts", url: "https://www.defense.gov/News/Contracts/"}] },
    { date: "2026-02-27", time: "18:00", tag: "CONTRACT", tagClass: "contract", text: '<strong>BAE Systems wins $500M+ U.S. Army Paladin howitzer contract</strong> for M109A7 production and sustainment. Artillery demand driven by Ukraine + Middle East escalation. <strong>TICKERS: BAESY.</strong>', recent: true, sources: [{name: "DoD Contracts", url: "https://www.defense.gov/News/Contracts/"}] },
    { date: "2026-02-27", time: "17:00", tag: "CONTRACT", tagClass: "contract", text: '<strong>General Dynamics Electric Boat wins $1.32B Navy contract</strong> for Virginia-class submarine construction support. Adds to multi-year sub production ramp. <strong>TICKERS: GD.</strong>', recent: true, sources: [{name: "DoD Contracts", url: "https://www.defense.gov/News/Contracts/"}] },
    { date: "2026-02-27", time: "15:00", tag: "CONTRACT", tagClass: "contract", text: '<strong>Lockheed wins $480M Navy contract</strong> for undersea warfare systems (ASW). Supports Navy modernization amid heightened Iran naval threat. <strong>TICKERS: LMT.</strong>', recent: true, sources: [{name: "DoD Contracts", url: "https://www.defense.gov/News/Contracts/"}] },
    { date: "2026-02-27", time: "13:00", tag: "POLYMARKET", tagClass: "polymarket", text: 'Polymarket odds: "Will US strike Iran by Feb 28?" surges from 17% to 73% in 48 hours. Heavy buying from new wallets flagged by Bubblemaps. Prediction market acting as early-warning indicator. <strong>TICKERS: LMT, RTX, NOC.</strong>', recent: true, sources: [{name: "Polymarket", url: "https://polymarket.com/"}] },
    { date: "2026-02-26", time: "21:00", tag: "CONTRACT", tagClass: "contract", text: '<strong>Rocket Lab wins $816M Space Development Agency contract</strong> for satellite manufacturing and launch services. Supports Golden Dome missile defense architecture. <strong>TICKERS: RKLB.</strong>', recent: true, sources: [{name: "DoD Contracts", url: "https://www.defense.gov/News/Contracts/"}] },
    { date: "2026-02-26", time: "18:00", tag: "OSINT", tagClass: "osint", text: 'ISW: US reportedly deploying additional SEAD assets to Gulf (F-16CJ, EA-18G) alongside carrier surge. Historical strike precursor pattern. <strong>TICKERS: LMT, RTX, LHX.</strong>', recent: true, sources: [{name: "ISW", url: "https://understandingwar.org/"}] },
    { date: "2026-02-26", time: "15:00", tag: "CONGRESS", tagClass: "congress", text: '<strong>Multiple defense committee members BUY RTX, LMT</strong> in days before Iran escalation. Unusual timing sparks insider trading scrutiny. Most traded: RTX. <strong>TICKERS: RTX, LMT.</strong>', recent: true, sources: [{name: "Capitol Trades", url: "https://www.capitoltrades.com/"}, {name: "Quiver Quant", url: "https://www.quiverquant.com/"}] },
    { date: "2026-02-25", time: "10:00", tag: "EARNINGS", tagClass: "earnings", text: '<strong>CrowdStrike earnings miss</strong> sends CRWD -9.85%. Downshift in growth and margin concerns. Removed from ETF basket. <strong>TICKERS: CRWD.</strong>', recent: true, sources: [{name: "CrowdStrike IR", url: "https://ir.crowdstrike.com/"}] },
    { date: "2026-02-24", time: "09:00", tag: "DOGE", tagClass: "doge", text: 'DOGE initiative targets federal IT/consulting spend. Services-heavy contractors (BAH, SAIC, LDOS) face budget compression risk. Hardware primes less exposed. <strong>TICKERS: BAH, SAIC, LDOS.</strong>', recent: true, sources: [{name: "Reuters", url: "https://www.reuters.com/"}] },
    { date: "2026-02-23", time: "16:00", tag: "CONTRACT", tagClass: "contract", text: 'Kratos awarded <strong>$12.4M CCA engine contract</strong> for Collaborative Combat Aircraft propulsion. Positions KTOS in NGAD ecosystem. <strong>TICKERS: KTOS, BA.</strong>', recent: true, sources: [{name: "Air Force Association", url: "https://www.afa.org/"}] },
    { date: "2026-02-23", time: "14:00", tag: "MILTRACK", tagClass: "miltrack", text: 'AFA Symposium: USAF confirms inert AIM-120 integration test on Boeing-built YFQ-44A CCA prototype. Indicates accelerated weapons integration timeline. <strong>TICKERS: BA, KTOS.</strong>', recent: true, sources: [{name: "Air Force Association", url: "https://www.afa.org/"}] },
    { date: "2026-02-22", time: "10:00", tag: "OSINT", tagClass: "osint", text: 'US C-17 airlift surge detected: 100+ flights toward CENTCOM staging bases in 48 hours. Comparable to early Iraq 2003 buildup. <strong>TICKERS: LMT, RTX, HII.</strong>', recent: true, sources: [{name: "ADS-B Exchange", url: "https://globe.adsbexchange.com/"}, {name: "@sentdefender", url: "https://x.com/sentdefender"}] },
    { date: "2026-02-20", time: "13:00", tag: "POLYMARKET", tagClass: "polymarket", text: 'Polymarket odds for "US strikes Iran by end of Feb" rise sharply as Pentagon pizza index spikes. Early warning triggered. <strong>TICKERS: LMT, RTX, NOC.</strong>', recent: true, sources: [{name: "Polymarket", url: "https://polymarket.com/"}, {name: "PizzINT", url: "https://pizzint.watch"}] },
    { date: "2026-02-18", time: "12:00", tag: "CYBER", tagClass: "cyber", text: 'Dragos report: Iran-linked APT groups targeting U.S. defense industrial base OT/ICS networks. Elevated cyber risk across primes and contractors. <strong>TICKERS: FTNT, PANW.</strong>', recent: true, sources: [{name: "Dragos", url: "https://www.dragos.com/"}] },
    { date: "2026-02-15", time: "09:00", tag: "OSINT", tagClass: "osint", text: 'USNI: SSGN Ohio-class submarine deployment confirmed to CENTCOM AOR amid Iran tensions. Increases strike capacity and signals imminent action. <strong>TICKERS: GD, HII.</strong>', recent: true, sources: [{name: "USNI News", url: "https://news.usni.org/"}] },
    { date: "2026-02-12", time: "10:00", tag: "POLYMARKET", tagClass: "polymarket", text: 'Polymarket begins listing multiple "US strikes Iran by..." markets with growing volume. Market becomes key early warning indicator. <strong>TICKERS: LMT, RTX, NOC.</strong>', recent: true, sources: [{name: "Polymarket", url: "https://polymarket.com/"}] },
    { date: "2026-02-10", time: "11:00", tag: "CONGRESS", tagClass: "congress", text: 'Capitol Trades: Unusual cluster of defense buys by HASC/SASC members in early Feb. Focus on RTX, LMT, PLTR. <strong>TICKERS: RTX, LMT, PLTR.</strong>', recent: false, sources: [{name: "Capitol Trades", url: "https://www.capitoltrades.com/"}] },
    { date: "2026-02-05", time: "16:00", tag: "OSINT", tagClass: "osint", text: 'Reports of increased IRGC naval activity in Strait of Hormuz; AIS spoofing and GPS jamming reported by commercial ships. Raises shipping risk. <strong>TICKERS: HII, GD, LMT.</strong>', recent: false, sources: [{name: "MARAD", url: "https://www.maritime.dot.gov/msci"}] },
    { date: "2026-02-01", time: "12:00", tag: "EARNINGS", tagClass: "earnings", text: 'LMT earnings beat; raised FY guidance on defense demand. Backlog record. <strong>TICKERS: LMT.</strong>', recent: false, sources: [{name: "Lockheed IR", url: "https://www.lockheedmartin.com/en-us/investor-relations.html"}] },
    { date: "2026-01-28", time: "08:00", tag: "POLYMARKET", tagClass: "polymarket", text: 'Polymarket begins pricing in elevated Iran strike probability; volume rising. <strong>TICKERS: LMT, RTX.</strong>', recent: false, sources: [{name: "Polymarket", url: "https://polymarket.com/"}] },
    { date: "2026-01-20", time: "09:00", tag: "DOGE", tagClass: "doge", text: 'DOGE federal spending freeze rumors intensify. Consulting/IT contractors face downside risk; hardware primes insulated. <strong>TICKERS: BAH, SAIC, LDOS.</strong>', recent: false, sources: [{name: "Reuters", url: "https://www.reuters.com/"}] },
    { date: "2026-01-15", time: "10:00", tag: "MILTRACK", tagClass: "miltrack", text: 'Unusual C-17 activity toward CENTCOM begins; early baseline breach. <strong>TICKERS: LMT, RTX.</strong>', recent: false, sources: [{name: "ADS-B Exchange", url: "https://globe.adsbexchange.com/"}] },
    { date: "2025-12-12", time: "12:00", tag: "CONTRACT", tagClass: "contract", text: 'NOC wins classified space payload contract; details withheld. <strong>TICKERS: NOC.</strong>', recent: false, sources: [{name: "DoD Contracts", url: "https://www.defense.gov/News/Contracts/"}] },
    { date: "2025-11-20", time: "14:00", tag: "CONGRESS", tagClass: "congress", text: 'Large RTX call option buys by members of Congress flagged by Unusual Whales. <strong>TICKERS: RTX.</strong>', recent: false, sources: [{name: "Unusual Whales", url: "https://unusualwhales.com/"}] },
    { date: "2025-10-15", time: "09:00", tag: "OSINT", tagClass: "osint", text: 'NATO increases readiness levels amid Russia tensions; defense primes benefit. <strong>TICKERS: LMT, RTX, NOC, BAESY.</strong>', recent: false, sources: [{name: "NATO", url: "https://www.nato.int/"}] },
    { date: "2025-09-01", time: "09:00", tag: "METHODOLOGY", tagClass: "method", text: 'Defense Signal Monitor methodology updated to include Polymarket, PizzINT, and MILTRACK scoring. Data sources expanded. <strong>TICKERS: ALL.</strong>', recent: false, sources: [{name: "DSM", url: "#"}] }
