    { date: "2026-02-24", time: "08:00", tag: "SPENDING", tagClass: "spending", text: "Pentagon releases <strong>$153B reconciliation spending plan</strong> — accelerating all into 2026. $29B shipbuilding, $24B munitions, $24B Golden Dome (classified), $16B readiness. <strong>B-21 production +25%</strong> ($4.5B). FY2027 target: $1.5T. <strong>BULLISH: NOC, HII, BWXT, RKLB.</strong>", recent: true, sources: [{name: "NY Times", url: "https://www.nytimes.com/2026/02/23/us/politics/pentagon-military-congress-spending.html"}, {name: "Defense One", url: "https://www.defenseone.com/threats/2026/02/the-d-brief-february-24-2026/411640/"}] },
    { date: "2026-02-24", time: "07:30", tag: "POLYMARKET", tagClass: "polymarket", text: "Polymarket: US strikes Iran by Feb 28 at <strong>16%</strong> ($40.1M vol). Mar 15: 51%. Mar 31: 63%. Jun 30: 71%. Total volume: <strong>$393M</strong>. Israel strikes Iran Feb 28: 14%. US/Israel strike by Dec 31: 77%. Russia-Ukraine ceasefire Feb 28: <strong>0%</strong>. Strike curve steepening.", recent: true, sources: [{name: "Polymarket", url: "https://polymarket.com/event/us-strikes-iran-by/us-strikes-iran-by-february-27-2026"}] },
    { date: "2026-02-24", time: "07:00", tag: "CONFLICT", tagClass: "conflict", text: "Robert Pape (U. Chicago): 'Never has the US deployed this much force and not launched strikes.' Hudson Institute: 'Force sufficient for weeks — <strong>2-week decision window</strong>.' Next Iran talks Thursday Geneva — last diplomatic window. <strong>CRITICAL.</strong>", recent: true, sources: [{name: "Alhurra", url: "https://alhurra.com/en/13586"}, {name: "Defense News", url: "https://www.defensenews.com/opinion/2026/02/24/the-us-air-force-needs-more-airpower-but-not-the-kind-its-buying/"}] },
    { date: "2026-02-23", time: "22:47", tag: "POLYMARKET", tagClass: "polymarket", text: "Polymarket: 'US next strikes Iran' — No strike by Feb 28 at <strong>80%</strong>. Feb 28 slot at 5.7%, Feb 27 at 5.2%. Total market volume: <strong>$43.4M+</strong>. Israel strikes Iran by Feb 28: <strong>14%</strong>. Markets pricing diplomacy window still open but tension elevated. <strong>BULLISH: LMT, RTX, NOC if window closes.</strong>", recent: true, sources: [{name: "Polymarket", url: "https://polymarket.com/event/us-next-strikes-iran-on-843/will-the-us-next-strike-iran-on-february-28-2026-et"}] },
    { date: "2026-02-23", time: "20:00", tag: "CONTRACT", tagClass: "contract", text: "AFA Warfare Symposium Day 1 (Aurora, CO): Air Force awards CCA engine contracts — KTOS/GE partnership receives <strong>$12.4M</strong> for GEK1500 (1,500-lb thrust) engine design; Honeywell receives parallel contract for SkyShot1600. Gen. Wilsbach confirms Anduril YFQ-44A CCA began weapons integration testing with inert AIM-120. <strong>BULLISH: KTOS, BA.</strong>", recent: true, sources: [{name: "Air & Space Forces Magazine", url: "https://www.airandspaceforces.com/air-force-taps-two-industry-teams-to-design-small-cca-engines/"}, {name: "FlightGlobal", url: "https://www.flightglobal.com/military-uavs/us-air-force-awards-cca-engine-contracts-to-honeywell-ge-kratos/166405.article"}] },
    { date: "2026-02-23", time: "10:30", tag: "CONTRACT", tagClass: "contract", text: "LMT secures potential <strong>$479.9M</strong> Navy 5-year contract for AN/SQQ-89A(V)15 anti-submarine warfare combat system (NAVSEA sole-source). Supports US Navy + Japan + Australia FMS. Parallel PAC-3 $43.5M quality/modernization award (cumulative $223M contract). <strong>BULLISH: LMT.</strong>", recent: true, sources: [{name: "GovCon Wire", url: "https://www.govconwire.com/articles/lockheed-480m-navy-asw-system-contract"}] },
    { date: "2026-02-23", time: "09:00", tag: "MILTRACK", tagClass: "miltrack", text: "CNN: US military positioned for 'multiple waves of strikes' into Iran. B-2 bomber movements being watched — analysts cite Cancian (CSIS): 'Observe any B-2 movements as indicator of Midnight Hammer repeat.' Diego Garcia UK base access dispute: UK PM Starmer tells Trump base cannot be used for Iran strikes; Trump fired back on Truth Social. <strong>ESCALATORY. Watch NOC (B-21), GD.</strong>", recent: true, sources: [{name: "CNN", url: "https://www.cnn.com/2026/02/23/politics/military-trump-iran-us-strike-mcgurk"}, {name: "Al Jazeera", url: "https://www.aljazeera.com/news/2026/2/20/tracking-the-rapid-us-military-build-up-near-iran"}] },
    { date: "2026-02-23", time: "08:00", tag: "OSINT", tagClass: "osint", text: "Stars & Stripes: Iran experts warn Tehran will respond with 'unrestrained' force if US strikes again. Iran Ambassador letter to UN Security Council: 'all bases, facilities and assets of hostile force in region constitute legitimate targets.' Iran signals closing the window on restrained response. <strong>ESCALATORY. BULLISH: ALL PRIMES, especially LMT, RTX, HII.</strong>", recent: true, sources: [{name: "Stars and Stripes", url: "https://www.stripes.com/theaters/middle_east/2026-02-23/iran-attacks-greater-strikes-20844844.html"}] },
    { date: "2026-02-23", time: "05:00", tag: "CYBER", tagClass: "cyber", text: "OPFOR Journal Feb 2026 Homeland Security Brief: Google Threat Intelligence Group (Feb 10) confirms Russia UNC5792/UNC5976, Iran UNC1549/UNC6446, China APT5, NK APT43 all running active social engineering campaigns against US defense contractor employees. Dragos (Feb 17): Chinese Voltzite/Azurite + Iranian Pyroxene APT groups embedding in US critical infrastructure/defense industry for pre-positioning. <strong>BULLISH: CRWD, FTNT, PLTR.</strong>", recent: true, sources: [{name: "OPFOR Journal", url: "https://www.opforjournal.com/p/homeland-security-brief-february"}, {name: "Dragos", url: "https://www.dragos.com/"}] },
    { date: "2026-02-22", time: "14:32", tag: "MILTRACK", tagClass: "miltrack", text: "12x F-22 Raptors (1st FW, Langley) staged at RAF Lakenheath, UK. Expected to continue to Middle East Monday. Tanker delay resolved. <strong>OSINT: @sentdefender, @havoc_aviation. BULLISH: LMT, LHX.</strong>", recent: true, sources: [{name: "@sentdefender", url: "https://x.com/sentdefender"}, {name: "ADS-B Exchange", url: "https://globe.adsbexchange.com/"}] },
    { date: "2026-02-22", time: "11:17", tag: "MILTRACK", tagClass: "miltrack", text: "10+ C-17A Globemaster IIIs airborne from east coast bound for Europe. Most originated Fort Hood, TX — likely air defense asset movement to Middle East. <strong>ADS-B Exchange confirmed. BULLISH: BA, LMT.</strong>", recent: true, sources: [{name: "ADS-B Exchange", url: "https://globe.adsbexchange.com/"}, {name: "Flightradar24", url: "https://www.flightradar24.com/"}] },
    { date: "2026-02-22", time: "08:45", tag: "MILTRACK", tagClass: "miltrack", text: "USS Gerald R. Ford (CVN-78) entered Mediterranean Sea. 2nd carrier heading to Middle East. Ford's 8th month deployed — redirected from Caribbean. <strong>Dual-carrier posture = PEAK force projection. BULLISH: HII, GD, NOC.</strong>", recent: true, sources: [{name: "MarineTraffic", url: "https://www.marinetraffic.com/"}, {name: "USNI News", url: "https://news.usni.org/"}] },
    { date: "2026-02-21", time: "19:03", tag: "OSINT", tagClass: "osint", text: "Sen. Lindsey Graham urges Trump to strike Iran after Middle East trip. Multiple officials cautioning restraint. Graham: 'opportunity for historic change.' <strong>OSINT: @sentdefender via Axios. ESCALATORY.</strong>", recent: true, sources: [{name: "Axios", url: "https://www.axios.com/"}, {name: "@sentdefender", url: "https://x.com/sentdefender"}] },
    { date: "2026-02-20", time: "16:41", tag: "MILTRACK", tagClass: "miltrack", text: "Pentagon surged 250+ aircraft to region: 64x C-17s to Al Udeid (Qatar), 31x C-17s to Prince Sultan (Saudi Arabia). Largest airlift since 2003 Iraq invasion. <strong>ADS-B/FR24 confirmed. BULLISH: ALL PRIMES.</strong>", recent: true, sources: [{name: "ADS-B Exchange", url: "https://globe.adsbexchange.com/"}, {name: "Flightradar24", url: "https://www.flightradar24.com/"}, {name: "Defense News", url: "https://www.defensenews.com/"}] },
    { date: "2026-02-20", time: "10:22", tag: "MILTRACK", tagClass: "miltrack", text: "USS Abraham Lincoln CSG confirmed operating in Arabian Sea near Oman via satellite imagery. CVW-9 includes F-35C (VMFA-314) and EA-18G Growler. <strong>Eurovision OSINT hex codes tracked. BULLISH: LMT, NOC.</strong>", recent: true, sources: [{name: "Eurovision OSINT", url: "https://spotlight.ebu.ch/p/iran-armada-osint-intelligence-guide"}, {name: "MarineTraffic", url: "https://www.marinetraffic.com/"}] },
        { date: "2026-02-20", time: "09:00", tag: "CONTRACT", tagClass: "contract", text: "RTX/Raytheon: US Navy officially approves <strong>StormBreaker smart weapon</strong> for operational use on F/A-18-E/F Super Hornet fleet. All-weather moving/fixed-target engagement. Already combat-proven; now integrating on F-35A/B/C. Expands RTX strike munitions franchise across entire carrier air wing. <strong>BULLISH: RTX, LMT (F-35 integration).</strong>", recent: true, sources: [{name: "RTX Press Release", url: "https://www.rtx.com/news/news-center/2026/02/20/u-s-navy-approves-raytheons-stormbreaker-smart-weapon-for-use-on-super-hornet"}] },
    { date: "2026-02-19", time: "13:18", tag: "MILTRACK", tagClass: "miltrack", text: "F-16CJ 'Wild Weasel' SEAD aircraft deploying to Middle East. Specialized in destroying enemy air defense radars — Iran-specific capability. <strong>Historically precedes strikes by 7-14 days. BULLISH: LMT, LHX.</strong>", recent: true, sources: [{name: "@AirSpecInt", url: "https://x.com/AirSpecInt"}, {name: "ADS-B Exchange", url: "https://globe.adsbexchange.com/"}] },
    { date: "2026-02-18", time: "09:56", tag: "MILTRACK", tagClass: "miltrack", text: "SSGN submarines (Ohio-class guided missile) reported deploying. Each carries 154 Tomahawk cruise missiles. Silent, undetectable first-strike platform. <strong>AIS dark confirmed. BULLISH: GD, RTX.</strong>", recent: true, sources: [{name: "USNI News", url: "https://news.usni.org/"}, {name: "@MT_Anderson", url: "https://x.com/MT_Anderson"}] },
    { date: "2026-02-15", time: "15:30", tag: "OSINT", tagClass: "osint", text: "AIS spoofing and GPS jamming surging in Strait of Hormuz. Iran seizing vessels claiming AIS non-transmission. USDOT MARAD Advisory 2026-001 issued Feb 9. <strong>Maritime risk ELEVATED. BULLISH: HII, LHX.</strong>", recent: true, sources: [{name: "MARAD Advisories", url: "https://www.maritime.dot.gov/msci"}, {name: "MarineTraffic", url: "https://www.marinetraffic.com/"}] },
    { date: "2026-02-09", time: "07:14", tag: "MILTRACK", tagClass: "miltrack", text: "P-8A Poseidon ISR patrol detected flying repeated tracks in Persian Gulf between Bahrain and UAE. KC-135 tanker briefly appeared near Iranian airspace before coverage cut. <strong>Pre-strike ISR pattern. BULLISH: NOC, RTX.</strong>", recent: true, sources: [{name: "ADS-B Exchange", url: "https://globe.adsbexchange.com/"}, {name: "r/ADSB", url: "https://www.reddit.com/r/ADSB/"}] },
    { date: "2026-02-07", time: "12:08", tag: "MILTRACK", tagClass: "miltrack", text: "112 C-17 Globemaster IIIs reported entering European/Middle East theater in single day. 12x C-17s at Ramstein (unusual), 5x at Al Udeid, 2x MQ-4C Tritons at Al Dhafra. <strong>Naval-technology.com OSINT. BULLISH: BA, LMT.</strong>", recent: true, sources: [{name: "Naval Technology", url: "https://www.naval-technology.com/"}, {name: "ADS-B Exchange", url: "https://globe.adsbexchange.com/"}] },
    { date: "2026-01-26", time: "10:00", tag: "MILTRACK", tagClass: "miltrack", text: "USS Abraham Lincoln CSG confirmed deployed to Middle East by CENTCOM. Escorts: USS Spruance, USS Frank E. Petersen Jr., USS Michael Murphy. CVW-9 with F-35C Lightning II. <strong>4th carrier deployment in 8 months (abnormal). BULLISH: LMT, HII.</strong>", recent: false, sources: [{name: "CENTCOM", url: "https://www.centcom.mil/"}, {name: "USNI News", url: "https://news.usni.org/"}] },
    { date: "2026-02-20", time: "18:15", tag: "CONFLICT", tagClass: "conflict", text: "Iran-US crisis at PEAK intensity. Two carrier strike groups deployed to Gulf. Reuters reports strikes possible within days. <strong>BULLISH: LMT, RTX, NOC, KTOS.</strong>", recent: true, sources: [{name: "Reuters Defense", url: "https://www.reuters.com/business/aerospace-defense/"}] },
    { date: "2026-02-19", time: "14:30", tag: "CONTRACT", tagClass: "contract", text: "Pentagon selects KTOS for Drone Dominance Program — <strong>$1.1B</strong> attritable UAS contract. Largest CCA award. <strong>BULLISH: KTOS, AVAV.</strong>", recent: true, sources: [{name: "DoD Contracts", url: "https://www.defense.gov/News/Contracts/"}, {name: "Defense News", url: "https://www.defensenews.com/"}] },
    { date: "2026-02-18", time: "16:02", tag: "SPENDING", tagClass: "spending", text: "LMT hits $666 52-week high. NOC hits $737. HII hits $443. Defense sector at all-time highs on <strong>$839B appropriation + Iran escalation</strong>.", recent: true, sources: [{name: "Perplexity Finance", url: "https://perplexity.ai/finance/LMT"}] },
    { date: "2026-02-14", time: "16:00", tag: "CONFLICT", tagClass: "conflict", text: "LDOS crashes to $173 (-11% in week). BAH continues slide to $77. <strong>DOGE risk materializing for IT services contractors.</strong>", recent: true, sources: [{name: "Perplexity Finance", url: "https://perplexity.ai/finance/LDOS"}] },
    { date: "2026-02-20", time: "21:30", tag: "POLYMARKET", tagClass: "polymarket", text: "US strikes Iran by Feb 28 surges to 19% (from 2%). <strong>$338M+ total volume on Iran strike timing. BULLISH: LMT, RTX, NOC.</strong>", recent: true, sources: [{name: "Polymarket", url: "https://polymarket.com/predictions/war"}] },
    { date: "2026-02-12", time: "09:45", tag: "POLYMARKET", tagClass: "polymarket", text: "Israeli authorities arrest traders for using <strong>classified military intelligence</strong> to place Polymarket bets. Prediction markets confirmed as intelligence leak vector.", recent: true, sources: [{name: "Reuters", url: "https://www.reuters.com/"}, {name: "Polymarket", url: "https://polymarket.com/"}] },
    { date: "2026-02-22", time: "06:00", tag: "CONFLICT", tagClass: "conflict", text: "ISW (Feb 22 assessment): Russia launched 347 drones/missiles overnight — <strong>shifting target set from energy to water/railway systems</strong> to interdict Ukrainian logistics. Included 4 hypersonic Zirkon cruise missiles. Ukrainian forces advanced near Kupyansk and Novopavlivka. Russia using Belarusian cellular infrastructure to coordinate drone strikes — NATO airspace incursions confirmed deliberate. <strong>Long-war narrative intact. BULLISH: LMT, RTX, AVAV, BAESY.</strong>", recent: true, sources: [{name: "Institute for the Study of War", url: "https://understandingwar.org/research/russia-ukraine/russian-offensive-campaign-assessment-february-22-2026/"}] },
    { date: "2026-02-12", time: "14:20", tag: "CONFLICT", tagClass: "conflict", text: "Trump-Putin peace talks collapse. Long war narrative reinforced. <strong>BULLISH: LMT, RTX, NOC, European defense</strong>", recent: false, sources: [{name: "Reuters", url: "https://www.reuters.com/"}] },
    { date: "2026-01-09", time: "10:30", tag: "TRADE", tagClass: "trade", text: "Rep. Cisneros (D-CA, HASC) buys RTX post-Venezuela op. <strong>HIGH SUSPICION.</strong>", recent: false, sources: [{name: "Capitol Trades", url: "https://www.capitoltrades.com/"}] },
    { date: "2026-01-07", time: "08:00", tag: "SPENDING", tagClass: "spending", text: "European defense stocks hit ATH on Greenland crisis. <strong>Rheinmetall +19%, Saab +22%</strong> in one week.", recent: false, sources: [{name: "Defense News", url: "https://www.defensenews.com/"}] },
    { date: "2026-01-03", time: "22:15", tag: "POLYMARKET", tagClass: "polymarket", text: "Polymarket trader turns $32K → $400K betting on Maduro ouster <strong>hours before US military operation</strong>. Insider trading on prediction markets now a national security concern.", recent: false, sources: [{name: "Polymarket", url: "https://polymarket.com/"}, {name: "Unusual Whales", url: "https://unusualwhales.com/"}] },
    { date: "2026-01-03", time: "06:00", tag: "CONFLICT", tagClass: "conflict", text: "US military captures Maduro in Venezuela. <strong>Defense stocks surge globally.</strong>", recent: false, sources: [{name: "Reuters Defense", url: "https://www.reuters.com/business/aerospace-defense/"}] },
    { date: "2025-12-29", time: "12:00", tag: "TRADE", tagClass: "trade", text: "Sen. Mullin (R-OK, SASC) buys RTX $15K-$50K + CVX $50K-$100K. <strong>5 days before Venezuela op. HIGHEST SUSPICION.</strong>", recent: false, sources: [{name: "Capitol Trades", url: "https://www.capitoltrades.com/"}, {name: "Quiver Quantitative", url: "https://www.quiverquant.com/"}] },
    { date: "2025-12-29", time: "09:00", tag: "DEPLOYMENT", tagClass: "deployment", text: "China \"Justice Mission 2025\" exercises — most extensive ever Taiwan drills.", recent: false, sources: [{name: "Reuters Defense", url: "https://www.reuters.com/business/aerospace-defense/"}] },
    { date: "2025-12-21", time: "15:00", tag: "SPENDING", tagClass: "spending", text: "FY2026 NDAA signed — <strong>$900.6B</strong>. First ever >$900B. <strong>BULLISH ALL PRIMES.</strong>", recent: false, sources: [{name: "Defense News", url: "https://www.defensenews.com/"}, {name: "DoD", url: "https://www.defense.gov/"}] },
    { date: "2025-12-17", time: "11:00", tag: "CONTRACT", tagClass: "contract", text: "$11.1B Taiwan arms sale — largest ever. HIMARS, ATACMS, Javelins. <strong>BULLISH: LMT, RTX.</strong>", recent: false, sources: [{name: "SIPRI", url: "https://www.sipri.org/"}, {name: "Defense News", url: "https://www.defensenews.com/"}] },
    { date: "2025-09-30", time: "14:00", tag: "CONTRACT", tagClass: "contract", text: "$24.3B F-35 Lots 18-19 to LMT. <strong>Largest consecutive F-35 contract ever.</strong>", recent: false, sources: [{name: "DoD Contracts", url: "https://www.defense.gov/News/Contracts/"}] },
    { date: "2025-09-03", time: "14:00", tag: "CONTRACT", tagClass: "contract", text: "$9.8B PAC-3 MSE to LMT. $900.5M Javelin to LMT/RTX.", recent: false, sources: [{name: "DoD Contracts", url: "https://www.defense.gov/News/Contracts/"}] },
    { date: "2025-08-01", time: "10:00", tag: "CONTRACT", tagClass: "contract", text: "$50B RTX Patriot sustainment through 2045. <strong>Largest missile defense contract ever.</strong>", recent: false, sources: [{name: "DoD Contracts", url: "https://www.defense.gov/News/Contracts/"}, {name: "Reuters Defense", url: "https://www.reuters.com/business/aerospace-defense/"}] },
    { date: "2025-06-25", time: "12:00", tag: "SPENDING", tagClass: "spending", text: "NATO agrees 5% GDP target. All 32 members exceed 2%. <strong>BULLISH: ALL DEFENSE.</strong>", recent: false, sources: [{name: "Defense News", url: "https://www.defensenews.com/"}, {name: "Reuters", url: "https://www.reuters.com/"}] },
    { date: "2025-06-13", time: "03:00", tag: "CONFLICT", tagClass: "conflict", text: "Israel/US strikes Iran nuclear sites. <strong>B-21 bombers (NOC) validated. Tomahawks (RTX) used.</strong>", recent: false, sources: [{name: "Reuters Defense", url: "https://www.reuters.com/business/aerospace-defense/"}, {name: "Al Jazeera", url: "https://www.aljazeera.com/"}] },
    { date: "2025-06-12", time: "18:59", tag: "PIZZINT", tagClass: "pizzint", text: "🍕 Pentagon Pizza Index spikes at 6:59 PM ET. Multiple pizza shops near Pentagon show \"much busier than usual\". <strong>Hours later: Israel strikes Iran nuclear sites.</strong>", recent: false, sources: [{name: "PizzINT", url: "https://pizzint.watch"}] },
    { date: "2025-05-30", time: "10:00", tag: "TRADE", tagClass: "trade", text: "Rep. Cisneros (D-CA, HASC) buys NOC, LHX, BA on same day. Sells LMT. <strong>Defense rotation.</strong>", recent: false, sources: [{name: "Capitol Trades", url: "https://www.capitoltrades.com/"}] },
    { date: "2025-05-13", time: "10:00", tag: "TRADE", tagClass: "trade", text: "Sen. Mullin (R-OK, SASC) buys L3Harris $15K-$50K. <strong>Defense spending increase looming.</strong>", recent: false, sources: [{name: "Capitol Trades", url: "https://www.capitoltrades.com/"}, {name: "OpenSecrets", url: "https://www.opensecrets.org/"}] }
];

// === POLITICIAN DATA ===
const politicianData = [
    { name: "Nancy Pelosi", party: "D-CA", committee: "Former Speaker — Classified Briefing Access", conflictLevel: "high-conflict", suspicion: "HIGH", suspicionClass: "high", summary: "MSFT calls before $22B IVAS contract. Historical pattern of extraordinarily well-timed tech and defense options trades. DEFCON 1: MAXIMUM ALERT." },
    { name: "Markwayne Mullin", party: "R-OK", committee: "SASC", conflictLevel: "high-conflict", suspicion: "HIGH", suspicionClass: "high", summary: "Bought RTX + CVX 5 days before Venezuela op. Bought L3Harris before spending increase. Most suspicious timing correlation in dataset." },
    { name: "Josh Gottheimer", party: "D-NJ", committee: "HPSCI", conflictLevel: "high-conflict", suspicion: "HIGH", suspicionClass: "high", summary: "#1 defense trader: $22M-$104M in 2024. Massive NOC, LMT, RTX positions. Intelligence committee access." },
    { name: "Scott Franklin", party: "R-FL", committee: "HASC / Approps", conflictLevel: "high-conflict", suspicion: "HIGH", suspicionClass: "high", summary: "Bought GD day after $1.32B Navy contract announced. Direct Appropriations Committee nexus." },
    { name: "Tommy Tuberville", party: "R-AL", committee: "SASC", conflictLevel: "high-conflict", suspicion: "HIGH", suspicionClass: "high", summary: "Held LMT during hearing with LMT CEO. Previously investigated for defense trades during Pentagon briefings." },
    { name: "Pat Fallon", party: "R-TX", committee: "HASC", conflictLevel: "high-conflict", suspicion: "HIGH", suspicionClass: "high", summary: "Held $250K Boeing during Boeing hearing. Pattern of holding stocks in companies he oversees." },
    { name: "Gilbert Cisneros", party: "D-CA", committee: "HASC", conflictLevel: "high-conflict", suspicion: "HIGH", suspicionClass: "high", summary: "Same-day NOC/LHX/BA buys; post-Venezuela RTX purchase. Active rotation across defense names from committee seat." }
];

// === THEATER DATA ===
const theaterData = [
    { name: "PACIFIC / CHINA", level: "HIGH", levelClass: "high", cardClass: "high", desc: "Taiwan 'Justice Mission 2025' — most extensive Chinese exercises ever. $11.1B Taiwan arms sale. Chinese Volt Typhoon cyber pre-positioning confirmed active. Submarine buildup accelerating. SDA satellite constellation expanding. $24B Golden Dome (classified). Middle East drawdown may temporarily reduce Pacific posture.", tickers: ["GD", "HII", "BWXT", "CW", "RKLB", "NOC"] },
    { name: "EUROPE / RUSSIA", level: "ELEVATED", levelClass: "elevated", cardClass: "elevated", desc: "Feb 24 = 4th anniversary Ukraine invasion. Russia launched 347 drones/missiles overnight Feb 21-22 — shifted to water/railway targets. 4x hypersonic Zirkon missiles used. NATO airspace incursions deliberate. All NATO 2%+ GDP, new 5% target. Front-line states accelerating orders. Trump-Putin talks collapsed Feb 12. Ceasefire odds: 0%.", tickers: ["LMT", "RTX", "AVAV", "BAESY"] },
    { name: "MIDDLE EAST", level: "⚠️ ACTIVE COMBAT", levelClass: "critical", cardClass: "critical", desc: "OPERATION EPIC FURY UNDERWAY. US and Israel conducting massive strike campaign across Iran. Khamenei reportedly killed (Israeli officials). 40+ regime figures eliminated. IDF struck 'hundreds of military sites.' Iran retaliating with missiles at Israel, US bases across Gulf. Dubai airport hit. CENTCOM: no US casualties, fleet fully operational. Trump: 'I can go long or end it in 2-3 days.'", tickers: ["LMT", "RTX", "NOC", "LHX", "KTOS", "HII", "GD", "BWXT"] },
    { name: "CYBER", level: "HIGH", levelClass: "high", cardClass: "high", desc: "State actors all targeting US defense contractors — Google TIG confirms Russia/China/Iran/NK campaigns. Dragos: Chinese/Iranian APTs embedding in critical infrastructure. AIS spoofing surge in Hormuz. FCC warns 4x telecom ransomware increase. Pentagon AI guardrails dispute. Google-Wiz $32B deal reshaping market.", tickers: ["CRWD", "PANW", "FTNT", "PLTR"] },
    { name: "CONUS / STRATEGIC", level: "ELEVATED", levelClass: "elevated", cardClass: "elevated", desc: "Nuclear modernization accelerating. $153B reconciliation spending — all into 2026. B-21 production +25% ($4.5B). Golden Dome $24B (classified). $1.5T FY2027 target. BWXT record $7.4B backlog. Iran eyeing CONUS proxy strikes per NYT.", tickers: ["NOC", "BWXT", "CW", "PLTR", "RKLB"] }
];

// === ETF DATA ===
const etfHoldings = [
    { ticker: "LMT", company: "Lockheed Martin", score: 5 },
    { ticker: "RTX", company: "Raytheon Technologies", score: 5 },
    { ticker: "NOC", company: "Northrop Grumman", score: 5 },